// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

arctica.wad
gfx/detail/arctic_incident/ai_detail.tga
gfx/env/snowlake_bk.tga
gfx/env/snowlake_dn.tga
gfx/env/snowlake_ft.tga
gfx/env/snowlake_lf.tga
gfx/env/snowlake_rt.tga
gfx/env/snowlake_up.tga
maps/arctic_incident_1.bsp
maps/arctic_incident_1_detail.txt
maps/arctic_incident_2_detail.txt
models/arctic_incident/agibs.mdl
models/arctic_incident/ambient_ant.mdl
models/arctic_incident/bomb.mdl
models/arctic_incident/chemlight.mdl
models/arctic_incident/chemlight_pack.mdl
models/arctic_incident/chillsquid.mdl
models/arctic_incident/coldtroller.mdl
models/arctic_incident/frost_agrunt.mdl
models/arctic_incident/garg.mdl
models/arctic_incident/headcrab.mdl
models/arctic_incident/HEVpilot.mdl
models/arctic_incident/hgrunt_pilot.mdl
models/arctic_incident/icebarnacle.mdl
models/arctic_incident/icelave.mdl
models/arctic_incident/islave_gibs1.mdl
models/arctic_incident/item_seckey.mdl
models/arctic_incident/land.mdl
models/arctic_incident/p_crossbow.mdl
models/arctic_incident/p_grenade.mdl
models/arctic_incident/p_pickaxe.mdl
models/arctic_incident/p_rpg.mdl
models/arctic_incident/polar_grunt.mdl
models/arctic_incident/rifleshell.mdl
models/arctic_incident/scmod/item_security.mdl
models/arctic_incident/w_battery.mdl
models/arctic_incident/w_crossbow_clip_ai.mdl
models/arctic_incident/w_grenade.mdl
models/arctic_incident/w_medkit.mdl
models/arctic_incident/w_pickaxe.mdl
models/arctic_incident/w_rpg.mdl
models/arctic_incident/w_rpgammo.mdl
models/arctic_incident/w_sqknest.mdl
models/arctic_incident/w_squeak.mdl
models/arctic_incident/white_hevarms/v_crossbow.mdl
models/arctic_incident/white_hevarms/v_grenade.mdl
models/arctic_incident/white_hevarms/v_medkit.mdl
models/arctic_incident/white_hevarms/v_pickaxe.mdl
models/arctic_incident/white_hevarms/v_rpg_ai.mdl
models/arctic_incident/white_hevplayer.mdl
sound/arctic_incident/ai_materials.txt
sound/arctic_incident/ambience/flareburn.wav
sound/arctic_incident/ambience/key_pickup.wav
sound/arctic_incident/ambience/key_unlocked.wav
sound/arctic_incident/ambience/light_loop.wav
sound/arctic_incident/ambience/sci_doomed.wav
sound/arctic_incident/ambience/sci_no.wav
sound/arctic_incident/ambience/wind.ogg
sound/arctic_incident/ambience/wind_cave.ogg
sound/arctic_incident/ambience/xtal_down1.wav
sound/arctic_incident/music/borealis.mp3
sound/arctic_incident/music/chained.mp3
sound/arctic_incident/player/pl_dirt1.wav
sound/arctic_incident/player/pl_dirt2.wav
sound/arctic_incident/player/pl_dirt3.wav
sound/arctic_incident/player/pl_dirt4.wav
sprites/arctic_incident/fire_fx.spr
sprites/arctic_incident/gargeye1.spr
sprites/arctic_incident/ins2/brf//weapon_ins2fnfal.txt
sprites/arctic_incident/ins2/hdg//weapon_ins2beretta.txt
sprites/arctic_incident/laserdot.spr
sprites/arctic_incident/scmod/item_key.spr
sprites/arctic_incident/scmod/item_keycard.spr
sprites/arctic_incident/weapon_crowbar.txt
sprites/arctic_incident/xspark4.spr
