maps/chess_v1.res
maps/chess_v1.cfg
maps/chess_v1_detail.txt
maps/chess_v1_motd.txt
sound/rng/chess/move1.ogg
sound/rng/chess/move2.ogg
sound/rng/chess/select.ogg
sound/rng/chess/turn.ogg
sound/rng/chess/reset.ogg
sound/rng/chess/reset2.ogg
sprites/chess/ch_arrow.spr
sprites/chess/ch_prob.spr
sprites/chess/ch_prob_f.spr
sprites/chess/ch_probf.spr
sprites/chess/ch_prow.spr
sprites/chess/ch_prow_f.spr
sprites/chess/ch_prowf.spr
gfx/detail/rng/chess1.tga
gfx/detail/rng/chess2.tga
gfx/detail/rng/chessm1.tga
gfx/detail/rng/chessm2.tga
gfx/detail/rng/strchessblack.tga
gfx/detail/rng/strchesswhite.tga
gfx/detail/rng/strchesstrim.tga
gfx/detail/rng/strchesspanels.tga
gfx/env/chessbkbk.tga
gfx/env/chessbkdn.tga
gfx/env/chessbkft.tga
gfx/env/chessbklf.tga
gfx/env/chessbkrt.tga
gfx/env/chessbkup.tga
gfx/env/chessbk2bk.tga
gfx/env/chessbk2dn.tga
gfx/env/chessbk2ft.tga
gfx/env/chessbk2lf.tga
gfx/env/chessbk2rt.tga
gfx/env/chessbk2up.tga