// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

maps/_player_sanctuary_materials.txt
gfx/env/digi_island_bk.tga
gfx/env/digi_island_dn.tga
gfx/env/digi_island_ft.tga
gfx/env/digi_island_lf.tga
gfx/env/digi_island_rt.tga
gfx/env/digi_island_up.tga
gfx/env/jazz_island_bk.tga
gfx/env/jazz_island_dn.tga
gfx/env/jazz_island_ft.tga
gfx/env/jazz_island_lf.tga
gfx/env/jazz_island_rt.tga
gfx/env/jazz_island_up.tga
gfx/env/waste_island_bk.tga
gfx/env/waste_island_dn.tga
gfx/env/waste_island_ft.tga
gfx/env/waste_island_lf.tga
gfx/env/waste_island_rt.tga
gfx/env/waste_island_up.tga
models/player/gabumon/gabumon.bmp
models/player/gabumon/gabumon.mdl
models/player/gabumon_b/gabumon_b.bmp
models/player/gabumon_b/gabumon_b.mdl
models/player/gabumon_c/gabumon_c.bmp
models/player/gabumon_c/gabumon_c.mdl
models/player/psychemon/psychemon.bmp
models/player/psychemon/psychemon.mdl
models/svboy/digilab/digi_chair.mdl
models/svboy/digilab/fences.mdl
models/svboy/digilab/gabu_notepad.mdl
models/svboy/digilab/gabumon_static.mdl
models/svboy/digilab/grass_island.mdl
models/svboy/digilab/grassy.mdl
models/svboy/digilab/rail.mdl
models/svboy/digilab/rail_post.mdl
models/svboy/digilab/sign.mdl
models/svboy/digilab/tree.mdl
models/svboy/digilab/trigger_camera.mdl
models/svboy/skel_player/backpack_sven.mdl
models/svboy/skel_player/crown.mdl
sound/sv_boy/digilab/buttons/click.ogg
sound/sv_boy/digilab/buttons/confirm.ogg
sound/sv_boy/digilab/buttons/deny.ogg
sound/sv_boy/digilab/buttons/digi_in.ogg
sound/sv_boy/digilab/buttons/digi_out.ogg
sound/sv_boy/digilab/buttons/feed.wav
sound/sv_boy/digilab/buttons/fuck.mp3
sound/sv_boy/digilab/buttons/hover.ogg
sound/sv_boy/digilab/buttons/list.ogg
sound/sv_boy/digilab/buttons/plop.ogg
sound/sv_boy/digilab/buttons/run.ogg
sound/sv_boy/digilab/buttons/spawn.ogg
sound/sv_boy/digilab/hq/mechwhine.wav
sound/sv_boy/digilab/hq/wind.ogg
sound/sv_boy/digilab/hq/wotah.ogg
sound/sv_boy/digilab/meow/w1.ogg
sound/sv_boy/digilab/meow/w2.ogg
sound/sv_boy/digilab/meow/w3.ogg
sound/sv_boy/digilab/music/all_spice.ogg
sound/sv_boy/digilab/music/digi_island.ogg
sound/sv_boy/digilab/music/digilab.ogg
sound/sv_boy/digilab/music/digilab_calm.ogg
sound/sv_boy/digilab/music/digilab_chill.ogg
sound/sv_boy/digilab/music/digilab_start.ogg
sound/sv_boy/digilab/music/edennav.ogg
sound/sv_boy/digilab/music/fudie.ogg
sound/sv_boy/digilab/music/fudie_start.ogg
sound/sv_boy/digilab/music/gato.ogg
sound/sv_boy/digilab/music/girlroom.ogg
sound/sv_boy/digilab/music/wasteland.ogg
sound/sv_boy/digilab/null.wav
sound/sv_boy/digilab/water1.ogg
sound/sv_boy/digilab/water2.ogg
sprites/svboy/cato.spr
sprites/svboy/fog.spr
sprites/svboy/LJ_airtank.spr
