// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

bts_rc.wad
developer_plates-1.wad
maps/bts_rc.gmr
maps/bts_rc.gsr
maps/bts_rc.res
maps/bts_rc_motd.txt
models/bts_rc/furniture/5ton.mdl
models/bts_rc/furniture/barrel.mdl
models/bts_rc/furniture/barrel2.mdl
models/bts_rc/furniture/barrel3.mdl
models/bts_rc/furniture/bigdoor.mdl
models/bts_rc/furniture/book_black.mdl
models/bts_rc/furniture/book_blue.mdl
models/bts_rc/furniture/book_red.mdl
models/bts_rc/furniture/bookshelf.mdl
models/bts_rc/furniture/bts_sign1.mdl
models/bts_rc/furniture/bts_sign2.mdl
models/bts_rc/furniture/cafeteria_chair.mdl
models/bts_rc/furniture/cafeteria_table.mdl
models/bts_rc/furniture/coffee_machine.mdl
models/bts_rc/furniture/couch.mdl
models/bts_rc/furniture/couch_station.mdl
models/bts_rc/furniture/dorms_table.mdl
models/bts_rc/furniture/eye_scanner_broken.mdl
models/bts_rc/furniture/forklift_static.mdl
models/bts_rc/furniture/gear.mdl
models/bts_rc/furniture/ladders.mdl
models/bts_rc/furniture/lambda.mdl
models/bts_rc/furniture/microwave.mdl
models/bts_rc/furniture/misc_healthstation1.mdl
models/bts_rc/furniture/misc_healthstation2.mdl
models/bts_rc/furniture/misc_map.mdl
models/bts_rc/furniture/misc_propaganda1.mdl
models/bts_rc/furniture/misc_suitcharger1.mdl
models/bts_rc/furniture/misc_toolchest.mdl
models/bts_rc/furniture/misc_vendingmachine1.mdl
models/bts_rc/furniture/misc_vendingmachine2.mdl
models/bts_rc/furniture/misc_vendingmachine3.mdl
models/bts_rc/furniture/misc_vendingmachine4.mdl
models/bts_rc/furniture/office_cabinet.mdl
models/bts_rc/furniture/office_cabinet2.mdl
models/bts_rc/furniture/office_cabinet3.mdl
models/bts_rc/furniture/office_cabinet4.mdl
models/bts_rc/furniture/office_computer1.mdl
models/bts_rc/furniture/office_computer2.mdl
models/bts_rc/furniture/office_computer3.mdl
models/bts_rc/furniture/office_partition.mdl
models/bts_rc/furniture/office_table.mdl
models/bts_rc/furniture/office_table_long.mdl
models/bts_rc/furniture/paper_note1.mdl
models/bts_rc/furniture/paper_page1.mdl
models/bts_rc/furniture/paper_page2.mdl
models/bts_rc/furniture/paper_page3.mdl
models/bts_rc/furniture/paper_page4.mdl
models/bts_rc/furniture/paper_page5.mdl
models/bts_rc/furniture/pool_table.mdl
models/bts_rc/furniture/pushcart.mdl
models/bts_rc/furniture/restroom_stalls.mdl
models/bts_rc/furniture/retina_component.mdl
models/bts_rc/furniture/shelf.mdl
models/bts_rc/furniture/shelf_short.mdl
models/bts_rc/furniture/shelf_storage1.mdl
models/bts_rc/furniture/shelf_storage2.mdl
models/bts_rc/furniture/shelf_storage3.mdl
models/bts_rc/furniture/shelf_storage4.mdl
models/bts_rc/furniture/shelf_storage5.mdl
models/bts_rc/furniture/sofa.mdl
models/bts_rc/furniture/storage_crate1.mdl
models/bts_rc/furniture/storage_crate2.mdl
models/bts_rc/furniture/storage_crate3.mdl
models/bts_rc/furniture/storage_crate4.mdl
models/bts_rc/furniture/storage_crate5.mdl
models/bts_rc/furniture/storage_crate6.mdl
models/bts_rc/furniture/storage_crate7.mdl
models/bts_rc/furniture/studycart.mdl
models/bts_rc/furniture/suv1.mdl
models/bts_rc/furniture/suv2.mdl
models/bts_rc/furniture/table.mdl
models/bts_rc/furniture/terrain_cliffs4.mdl
models/bts_rc/furniture/terrain_cliffs5.mdl
models/bts_rc/furniture/tower.mdl
models/bts_rc/furniture/trashcan.mdl
models/bts_rc/furniture/truck_research.mdl
models/bts_rc/furniture/tv.mdl
models/bts_rc/furniture/tv_unit.mdl
models/bts_rc/furniture/valve.mdl
models/bts_rc/furniture/w_flashlightbattery.mdl
models/bts_rc/furniture/warehouse_shelf.mdl
models/bts_rc/furniture/wires1.mdl
models/bts_rc/furniture/wires2.mdl
models/bts_rc/monsters/agrunt.mdl
models/bts_rc/monsters/bullsquid.mdl
models/bts_rc/monsters/civ_paper_scientist.mdl
models/bts_rc/monsters/gonome.mdl
models/bts_rc/monsters/gonome_barney.mdl
models/bts_rc/monsters/gonome_soldier.mdl
models/bts_rc/monsters/headcrab.mdl
models/bts_rc/monsters/hgrunt.mdl
models/bts_rc/monsters/hgrunt_medic.mdl
models/bts_rc/monsters/hgrunt_opfor.mdl
models/bts_rc/monsters/hgrunt_torch.mdl
models/bts_rc/monsters/hgrunt_torch01.mdl
models/bts_rc/monsters/hgrunt_torch02.mdl
models/bts_rc/monsters/hwgrunt.mdl
models/bts_rc/monsters/islave.mdl
models/bts_rc/monsters/massn.mdl
models/bts_rc/monsters/scientist.mdl
models/bts_rc/monsters/scientist2.mdl
models/bts_rc/monsters/sentry_blkops.mdl
models/bts_rc/monsters/sentry_blkopst.mdl
models/bts_rc/monsters/snapbug.mdl
models/bts_rc/monsters/zombie.mdl
models/bts_rc/monsters/zombie_barney.mdl
models/bts_rc/monsters/zombie_blackops.mdl
models/bts_rc/monsters/zombie_construction.mdl
models/bts_rc/monsters/zombie_engineer.mdl
models/bts_rc/monsters/zombie_hev.mdl
models/bts_rc/monsters/zombie_worker.mdl
models/bts_rc/weapons/barney_helmet.mdl
models/bts_rc/weapons/barney_vest.mdl
models/bts_rc/weapons/dart.mdl
models/bts_rc/weapons/flare.mdl
models/bts_rc/weapons/flaret.mdl
models/bts_rc/weapons/p_357.mdl
models/bts_rc/weapons/p_9mmAR.mdl
models/bts_rc/weapons/p_9mmARGL.mdl
models/bts_rc/weapons/p_9mmhandgun.mdl
models/bts_rc/weapons/p_9mmhandgunsd.mdl
models/bts_rc/weapons/p_axe.mdl
models/bts_rc/weapons/p_beretta.mdl
models/bts_rc/weapons/p_crowbar.mdl
models/bts_rc/weapons/p_crowbarb.mdl
models/bts_rc/weapons/p_crowbaro.mdl
models/bts_rc/weapons/p_dartgun.mdl
models/bts_rc/weapons/p_desert_eagle.mdl
models/bts_rc/weapons/p_flare.mdl
models/bts_rc/weapons/p_flashlight.mdl
models/bts_rc/weapons/p_m16.mdl
models/bts_rc/weapons/p_m4.mdl
models/bts_rc/weapons/p_m4sd.mdl
models/bts_rc/weapons/p_m79.mdl
models/bts_rc/weapons/p_medkit.mdl
models/bts_rc/weapons/p_pipe.mdl
models/bts_rc/weapons/p_pipe_wrench.mdl
models/bts_rc/weapons/p_poolstick.mdl
models/bts_rc/weapons/p_sbshotgun.mdl
models/bts_rc/weapons/p_screwdriver.mdl
models/bts_rc/weapons/p_shotgun.mdl
models/bts_rc/weapons/v_357.mdl
models/bts_rc/weapons/v_9mmAR.mdl
models/bts_rc/weapons/v_9mmARGL.mdl
models/bts_rc/weapons/v_9mmhandgun.mdl
models/bts_rc/weapons/v_9mmhandgunsd.mdl
models/bts_rc/weapons/v_axe.mdl
models/bts_rc/weapons/v_beretta.mdl
models/bts_rc/weapons/v_crowbar.mdl
models/bts_rc/weapons/v_crowbarb.mdl
models/bts_rc/weapons/v_crowbaro.mdl
models/bts_rc/weapons/v_dartgun.mdl
models/bts_rc/weapons/v_desert_eagle.mdl
models/bts_rc/weapons/v_flare.mdl
models/bts_rc/weapons/v_flaregun.mdl
models/bts_rc/weapons/v_flashlight.mdl
models/bts_rc/weapons/v_glock18.mdl
models/bts_rc/weapons/v_grenade.mdl
models/bts_rc/weapons/v_knife.mdl
models/bts_rc/weapons/v_m16a2.mdl
models/bts_rc/weapons/v_m4.mdl
models/bts_rc/weapons/v_m4sd.mdl
models/bts_rc/weapons/v_m79.mdl
models/bts_rc/weapons/v_medkit.mdl
models/bts_rc/weapons/v_pipe.mdl
models/bts_rc/weapons/v_pipe_wrench.mdl
models/bts_rc/weapons/v_poolstick.mdl
models/bts_rc/weapons/v_saw.mdl
models/bts_rc/weapons/v_sbshotgun.mdl
models/bts_rc/weapons/v_screwdriver.mdl
models/bts_rc/weapons/v_shotgun.mdl
models/bts_rc/weapons/w_357.mdl
models/bts_rc/weapons/w_556nato.mdl
models/bts_rc/weapons/w_9mmar.mdl
models/bts_rc/weapons/w_9mmarclip.mdl
models/bts_rc/weapons/w_9mmarGL.mdl
models/bts_rc/weapons/w_9mmclip.mdl
models/bts_rc/weapons/w_9mmhandgun.mdl
models/bts_rc/weapons/w_9mmhandgunsd.mdl
models/bts_rc/weapons/w_9mmhandgunsdt.mdl
models/bts_rc/weapons/w_axe.mdl
models/bts_rc/weapons/w_beretta.mdl
models/bts_rc/weapons/w_crowbar.mdl
models/bts_rc/weapons/w_crowbarb.mdl
models/bts_rc/weapons/w_crowbaro.mdl
models/bts_rc/weapons/w_dartgun.mdl
models/bts_rc/weapons/w_dartgun_clip.mdl
models/bts_rc/weapons/w_desert_eagle.mdl
models/bts_rc/weapons/w_flare.mdl
models/bts_rc/weapons/w_flaregun_clip.mdl
models/bts_rc/weapons/w_flaret.mdl
models/bts_rc/weapons/w_flashlight.mdl
models/bts_rc/weapons/w_m16.mdl
models/bts_rc/weapons/w_m4.mdl
models/bts_rc/weapons/w_m4sd.mdl
models/bts_rc/weapons/w_m79.mdl
models/bts_rc/weapons/w_medkit.mdl
models/bts_rc/weapons/w_mp5_clip.mdl
models/bts_rc/weapons/w_pipe.mdl
models/bts_rc/weapons/w_pipe_wrench.mdl
models/bts_rc/weapons/w_pmedkit.mdl
models/bts_rc/weapons/w_poolstick.mdl
models/bts_rc/weapons/w_saw.mdl
models/bts_rc/weapons/w_sbshotgun.mdl
models/bts_rc/weapons/w_screwdriver.mdl
models/bts_rc/weapons/w_screwdrivert.mdl
models/bts_rc/weapons/w_shotgun.mdl
models/player/bts_barney/bts_barney.mdl
models/player/bts_construction/bts_construction.mdl
models/player/bts_helmet/bts_helmet.mdl
models/player/bts_otis/bts_otis.mdl
models/player/bts_scientist/bts_scientist.mdl
models/player/bts_scientist2/bts_scientist2.mdl
models/player/bts_scientist3/bts_scientist3.mdl
models/player/bts_scientist4/bts_scientist4.mdl
scripts/maps/bts_rc/bts_rc_register.as
scripts/maps/bts_rc/hl_utils.as
scripts/maps/bts_rc/list_weapons.as
scripts/maps/bts_rc/mappings.as
scripts/maps/bts_rc/player_voices/player_voices.as
scripts/maps/bts_rc/point_checkpoint.as
scripts/maps/bts_rc/proj/proj_flare.as
scripts/maps/bts_rc/trigger_shuffle_position.as
scripts/maps/bts_rc/weapons/weapon_bts_axe.as
scripts/maps/bts_rc/weapons/weapon_bts_beretta.as
scripts/maps/bts_rc/weapons/weapon_bts_crowbar.as
scripts/maps/bts_rc/weapons/weapon_bts_dartgun.as
scripts/maps/bts_rc/weapons/weapon_bts_eagle.as
scripts/maps/bts_rc/weapons/weapon_bts_flare.as
scripts/maps/bts_rc/weapons/weapon_bts_flaregun.as
scripts/maps/bts_rc/weapons/weapon_bts_flashlight.as
scripts/maps/bts_rc/weapons/weapon_bts_glock.as
scripts/maps/bts_rc/weapons/weapon_bts_glock18.as
scripts/maps/bts_rc/weapons/weapon_bts_glocksd.as
scripts/maps/bts_rc/weapons/weapon_bts_handgrenade.as
scripts/maps/bts_rc/weapons/weapon_bts_knife.as
scripts/maps/bts_rc/weapons/weapon_bts_m16.as
scripts/maps/bts_rc/weapons/weapon_bts_m4.as
scripts/maps/bts_rc/weapons/weapon_bts_m4sd.as
scripts/maps/bts_rc/weapons/weapon_bts_m79.as
scripts/maps/bts_rc/weapons/weapon_bts_mp5.as
scripts/maps/bts_rc/weapons/weapon_bts_mp5gl.as
scripts/maps/bts_rc/weapons/weapon_bts_pipe.as
scripts/maps/bts_rc/weapons/weapon_bts_poolstick.as
scripts/maps/bts_rc/weapons/weapon_bts_python.as
scripts/maps/bts_rc/weapons/weapon_bts_saw.as
scripts/maps/bts_rc/weapons/weapon_bts_sbshotgun.as
scripts/maps/bts_rc/weapons/weapon_bts_screwdriver.as
scripts/maps/bts_rc/weapons/weapon_bts_shotgun.as
sound/bts_rc/ambience/d4_water.wav
sound/bts_rc/ambience/d5_warning.wav
sound/bts_rc/ambience/d5_warning_alt.wav
sound/bts_rc/ambience/hecu_ambience1.wav
sound/bts_rc/ambience/hecu_ambience2.wav
sound/bts_rc/ambience/hecu_ambience3.wav
sound/bts_rc/ambience/hecu_ambience4.wav
sound/bts_rc/ambience/hecu_ambience5.wav
sound/bts_rc/ambience/hecu_radio1.wav
sound/bts_rc/fmbw.wav
sound/bts_rc/fvox/hev_automatic_ap.wav
sound/bts_rc/fvox/hev_automatic_hp.wav
sound/bts_rc/fvox/hev_logon.wav
sound/bts_rc/gonome_hecu.txt
sound/bts_rc/gonome_hecu/gonome_idle1.wav
sound/bts_rc/interference.wav
sound/bts_rc/interference2.wav
sound/bts_rc/items/9mmclip1.wav
sound/bts_rc/items/9mmclip2.wav
sound/bts_rc/items/9mmcock3.wav
sound/bts_rc/items/barrier.wav
sound/bts_rc/items/battery_pickup1.wav
sound/bts_rc/items/d1_equipment.wav
sound/bts_rc/items/d3_sink.wav
sound/bts_rc/items/flare_pickup1.wav
sound/bts_rc/items/flashlight1.wav
sound/bts_rc/items/mag_flip.wav
sound/bts_rc/items/medcharge4.wav
sound/bts_rc/items/medshotno1.wav
sound/bts_rc/items/power_fail.wav
sound/bts_rc/items/power_online.wav
sound/bts_rc/items/repair_snd1.wav
sound/bts_rc/items/repair_snd2.wav
sound/bts_rc/items/repair_snd3.wav
sound/bts_rc/items/repair_snd4.wav
sound/bts_rc/items/repair_snd5.wav
sound/bts_rc/massn.txt
sound/bts_rc/music/bts_rc_checkpoint.ogg
sound/bts_rc/music/bts_rc_credits.ogg
sound/bts_rc/music/bts_rc_credits_alt.ogg
sound/bts_rc/music/bts_rc_credits_alt2.ogg
sound/bts_rc/music/bts_rc_credits_alt3.ogg
sound/bts_rc/music/bts_rc_intro.ogg
sound/bts_rc/music/resonance.wav
sound/bts_rc/music/sewers.wav
sound/bts_rc/player/construction/co_die1.wav
sound/bts_rc/player/construction/co_die2.wav
sound/bts_rc/player/construction/co_die3.wav
sound/bts_rc/player/construction/co_die4.wav
sound/bts_rc/player/construction/co_pain1.wav
sound/bts_rc/player/construction/co_pain2.wav
sound/bts_rc/player/construction/co_pain3.wav
sound/bts_rc/player/construction/co_pain4.wav
sound/bts_rc/player/generic/pl_burn1.wav
sound/bts_rc/player/generic/pl_burn2.wav
sound/bts_rc/player/generic/pl_death1.wav
sound/bts_rc/player/generic/pl_death2.wav
sound/bts_rc/player/generic/pl_death3.wav
sound/bts_rc/player/generic/pl_death4.wav
sound/bts_rc/player/generic/pl_pain1.wav
sound/bts_rc/player/generic/pl_pain2.wav
sound/bts_rc/player/generic/pl_pain3.wav
sound/bts_rc/player/generic/pl_pain4.wav
sound/bts_rc/player/generic/pl_pain5.wav
sound/bts_rc/player/helmet/hm_death1.wav
sound/bts_rc/player/helmet/hm_death2.wav
sound/bts_rc/player/helmet/hm_death3.wav
sound/bts_rc/player/helmet/hm_death4.wav
sound/bts_rc/player/helmet/hm_pain1.wav
sound/bts_rc/player/helmet/hm_pain2.wav
sound/bts_rc/player/helmet/hm_pain3.wav
sound/bts_rc/player/helmet/hm_pain4.wav
sound/bts_rc/player/helmet/hm_pain5.wav
sound/bts_rc/scientist/sc_area12.wav
sound/bts_rc/scientist/sc_area45.wav
sound/bts_rc/scientist/sci_adminroom.wav
sound/bts_rc/scientist/sci_end.wav
sound/bts_rc/scientist/sci_foreshadow1.wav
sound/bts_rc/scientist/sci_foreshadow2.wav
sound/bts_rc/scientist/sci_foreshadow3.wav
sound/bts_rc/scientist/sci_foreshadow4.wav
sound/bts_rc/scientist/sci_foreshadow5.wav
sound/bts_rc/scientist/sci_interferance.wav
sound/bts_rc/scientist/sci_intro.wav
sound/bts_rc/scientist/sci_intro2.wav
sound/bts_rc/scientist/sci_keyitems.wav
sound/bts_rc/scientist/sci_poke1.wav
sound/bts_rc/scientist/sci_poke2.wav
sound/bts_rc/scientist/sci_poke3.wav
sound/bts_rc/scientist/sci_sample.wav
sound/bts_rc/scientist/sci_simulation.wav
sound/bts_rc/sentry/tu_deploy.wav
sound/bts_rc/sentry/tu_die.wav
sound/bts_rc/sentry/tu_die2.wav
sound/bts_rc/sentry/tu_die3.wav
sound/bts_rc/sentry/tu_fire1.wav
sound/bts_rc/sentry/tu_ping.wav
sound/bts_rc/sentry_blackops.txt
sound/bts_rc/tride/a1_arrive.wav
sound/bts_rc/tride/a1_inbound.wav
sound/bts_rc/tride/a4_arrive.wav
sound/bts_rc/tride/a4_inbound.wav
sound/bts_rc/vox/blackops_announcement.wav
sound/bts_rc/vox/d1_lockdown_offline.wav
sound/bts_rc/vox/d1_lockdown_online.wav
sound/bts_rc/vox/d1_retina.wav
sound/bts_rc/vox/d1_sentries_offline.wav
sound/bts_rc/vox/d1_sentries_online.wav
sound/bts_rc/vox/d1d4_tram_online.wav
sound/bts_rc/vox/d2_generatorpwr.wav
sound/bts_rc/vox/d2_generatorpwr2.wav
sound/bts_rc/vox/d3_bridge.wav
sound/bts_rc/vox/d3_power_off.wav
sound/bts_rc/vox/d3_power_on.wav
sound/bts_rc/vox/d4_chemical.wav
sound/bts_rc/vox/d4_lockdown_online.wav
sound/bts_rc/vox/intro.wav
sound/bts_rc/vox/military_announcement.wav
sound/bts_rc/weapons/9mm_clip.wav
sound/bts_rc/weapons/9mm_clipout.wav
sound/bts_rc/weapons/9mm_cock1.wav
sound/bts_rc/weapons/9mm_cock2.wav
sound/bts_rc/weapons/9mm_draw.wav
sound/bts_rc/weapons/9mm_in.wav
sound/bts_rc/weapons/axe_hit1.wav
sound/bts_rc/weapons/axe_hit2.wav
sound/bts_rc/weapons/axe_hitbod1.wav
sound/bts_rc/weapons/axe_hitbod2.wav
sound/bts_rc/weapons/axe_hitbod3.wav
sound/bts_rc/weapons/axe_miss1.wav
sound/bts_rc/weapons/beretta_draw.wav
sound/bts_rc/weapons/beretta_fire1.wav
sound/bts_rc/weapons/dartgun_chargedown.wav
sound/bts_rc/weapons/dartgun_chargeloop.wav
sound/bts_rc/weapons/dartgun_chargestop.wav
sound/bts_rc/weapons/dartgun_chargeup.wav
sound/bts_rc/weapons/dartgun_fire1.wav
sound/bts_rc/weapons/desert_eagle_reload.wav
sound/bts_rc/weapons/fidget_2.wav
sound/bts_rc/weapons/fidget_3.wav
sound/bts_rc/weapons/fidget_4.wav
sound/bts_rc/weapons/flare_bounce.wav
sound/bts_rc/weapons/flare_deploy.wav
sound/bts_rc/weapons/flare_on.wav
sound/bts_rc/weapons/flare_pinpull.wav
sound/bts_rc/weapons/flaregun_draw.wav
sound/bts_rc/weapons/flaregun_reload1.wav
sound/bts_rc/weapons/flaregun_reload2.wav
sound/bts_rc/weapons/flaregun_shot1.wav
sound/bts_rc/weapons/flashlight_hit1.wav
sound/bts_rc/weapons/flashlight_hit2.wav
sound/bts_rc/weapons/flashlight_hitbod1.wav
sound/bts_rc/weapons/flashlight_hitbod2.wav
sound/bts_rc/weapons/flashlight_hitbod3.wav
sound/bts_rc/weapons/flashlight_miss1.wav
sound/bts_rc/weapons/glock18_fire1.wav
sound/bts_rc/weapons/glock_fire1.wav
sound/bts_rc/weapons/glocksd_fire1.wav
sound/bts_rc/weapons/glocksd_fire2.wav
sound/bts_rc/weapons/grenade_draw.wav
sound/bts_rc/weapons/grenade_pinpull.wav
sound/bts_rc/weapons/grenade_throw1.wav
sound/bts_rc/weapons/grenade_throw2.wav
sound/bts_rc/weapons/m16_burst1.wav
sound/bts_rc/weapons/m16_fire1.wav
sound/bts_rc/weapons/m16sd_burst1.wav
sound/bts_rc/weapons/m203_close.wav
sound/bts_rc/weapons/m203_in.wav
sound/bts_rc/weapons/m203_open.wav
sound/bts_rc/weapons/m203_shell.wav
sound/bts_rc/weapons/m4_clic1.wav
sound/bts_rc/weapons/m4_clipinsert1.wav
sound/bts_rc/weapons/m4_cliprelease1.wav
sound/bts_rc/weapons/m4_fire1.wav
sound/bts_rc/weapons/m4sd_fire1.wav
sound/bts_rc/weapons/m79_aimon.wav
sound/bts_rc/weapons/m79_close.wav
sound/bts_rc/weapons/m79_fire.wav
sound/bts_rc/weapons/m79_open.wav
sound/bts_rc/weapons/m79_shellin.wav
sound/bts_rc/weapons/m79_shellout.wav
sound/bts_rc/weapons/mp5_clipout.wav
sound/bts_rc/weapons/mp5_draw.wav
sound/bts_rc/weapons/mp5_draw2.wav
sound/bts_rc/weapons/mp5_fire1.wav
sound/bts_rc/weapons/mp5_fire2.wav
sound/bts_rc/weapons/mp5_fire3.wav
sound/bts_rc/weapons/mp5_in.wav
sound/bts_rc/weapons/mp5_slap.wav
sound/bts_rc/weapons/pipe_hit1.wav
sound/bts_rc/weapons/pipe_hit2.wav
sound/bts_rc/weapons/pipe_hitbod1.wav
sound/bts_rc/weapons/pipe_hitbod2.wav
sound/bts_rc/weapons/pipe_hitbod3.wav
sound/bts_rc/weapons/pipe_miss1.wav
sound/bts_rc/weapons/reload1.wav
sound/bts_rc/weapons/reload3.wav
sound/bts_rc/weapons/saw_fire1.wav
sound/bts_rc/weapons/saw_reload.wav
sound/bts_rc/weapons/saw_reload2.wav
sound/bts_rc/weapons/sbshotgun_fire1.wav
sound/bts_rc/weapons/scock1.wav
sound/bts_rc/weapons/sd_hit1.wav
sound/bts_rc/weapons/sd_hit2.wav
sound/bts_rc/weapons/sd_hitbod1.wav
sound/bts_rc/weapons/sd_hitbod2.wav
sound/bts_rc/weapons/sd_hitbod3.wav
sound/bts_rc/weapons/sd_miss1.wav
sound/bts_rc/weapons/spas12_dbarrel1.wav
sound/bts_rc/weapons/spas12_foley.wav
sound/bts_rc/weapons/spas_idle4.wav
sound/bts_rc/zombie_hev.txt
sound/bts_rc/zombie_hev/zo_alert10.wav
sound/bts_rc/zombie_hev/zo_alert20.wav
sound/bts_rc/zombie_hev/zo_alert30.wav
sound/bts_rc/zombie_hev/zo_attack1.wav
sound/bts_rc/zombie_hev/zo_attack2.wav
sound/bts_rc/zombie_hev/zo_death1.wav
sound/bts_rc/zombie_hev/zo_death2.wav
sound/bts_rc/zombie_hev/zo_idle1.wav
sound/bts_rc/zombie_hev/zo_idle2.wav
sound/bts_rc/zombie_hev/zo_idle3.wav
sound/bts_rc/zombie_hev/zo_idle4.wav
sound/bts_rc/zombie_hev/zo_pain1.wav
sound/bts_rc/zombie_hev/zo_pain2.wav
sprites/bts_rc/640hudof01.spr
sprites/bts_rc/640hudof02.spr
sprites/bts_rc/ammo_battery.spr
sprites/bts_rc/ammo_flare.spr
sprites/bts_rc/flare_selection.spr
sprites/bts_rc/inv_card_maint.spr
sprites/bts_rc/inv_card_research.spr
sprites/bts_rc/inv_card_security.spr
sprites/bts_rc/M79_crosshair.spr
sprites/bts_rc/muzzleflash12.spr
sprites/bts_rc/screwd.spr
sprites/bts_rc/w_beretta.spr
sprites/bts_rc/w_glocksd1.spr
sprites/bts_rc/w_glocksd4.spr
sprites/bts_rc/weapon_knife.spr
sprites/bts_rc/weapon_M79.spr
sprites/bts_rc/weapons/weapon_bts_axe.txt
sprites/bts_rc/weapons/weapon_bts_beretta.txt
sprites/bts_rc/weapons/weapon_bts_crowbar.txt
sprites/bts_rc/weapons/weapon_bts_dartgun.txt
sprites/bts_rc/weapons/weapon_bts_eagle.txt
sprites/bts_rc/weapons/weapon_bts_flare.txt
sprites/bts_rc/weapons/weapon_bts_flashlight.txt
sprites/bts_rc/weapons/weapon_bts_glock.txt
sprites/bts_rc/weapons/weapon_bts_glock18.txt
sprites/bts_rc/weapons/weapon_bts_glocksd.txt
sprites/bts_rc/weapons/weapon_bts_handgrenade.txt
sprites/bts_rc/weapons/weapon_bts_knife.txt
sprites/bts_rc/weapons/weapon_bts_m16.txt
sprites/bts_rc/weapons/weapon_bts_m4.txt
sprites/bts_rc/weapons/weapon_bts_m4sd.txt
sprites/bts_rc/weapons/weapon_bts_m79.txt
sprites/bts_rc/weapons/weapon_bts_mp5.txt
sprites/bts_rc/weapons/weapon_bts_mp5gl.txt
sprites/bts_rc/weapons/weapon_bts_pipe.txt
sprites/bts_rc/weapons/weapon_bts_poolstick.txt
sprites/bts_rc/weapons/weapon_bts_sbshotgun.txt
sprites/bts_rc/weapons/weapon_bts_screwdriver.txt
sprites/bts_rc/weapons/weapon_bts_shotgun.txt
sprites/bts_rc/wepspr.spr
sprites/bts_rc/zerogxplode.spr
