// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

cg_caged.wad
cg_hl.wad
cg_os_platform.wad
entity.wad
gfx/env/grimmnightbk.tga
gfx/env/grimmnightdn.tga
gfx/env/grimmnightft.tga
gfx/env/grimmnightlf.tga
gfx/env/grimmnightrt.tga
gfx/env/grimmnightup.tga
models/caged/agibs.mdl
models/caged/can.mdl
models/caged/can2.mdl
models/caged/cg_binder01.mdl
models/caged/cg_binder02.mdl
models/caged/cg_boomgibs.mdl
models/caged/cg_bulb01.mdl
models/caged/cg_can02.mdl
models/caged/cg_cardboard.mdl
models/caged/cg_cardboard2.mdl
models/caged/cg_cboards01.mdl
models/caged/cg_crossbow.mdl
models/caged/cg_crossbow_clip.mdl
models/caged/cg_hallwire01.mdl
models/caged/cg_oldcan01.mdl
models/caged/cg_oldcan02.mdl
models/caged/cg_oldcan03.mdl
models/caged/cg_patient0.mdl
models/caged/cg_patient_d.mdl
models/caged/cg_pboxwire01.mdl
models/caged/cg_ratgibs.mdl
models/caged/cg_reels01.mdl
models/caged/cg_reels02.mdl
models/caged/cg_reels03.mdl
models/caged/cg_soap02.mdl
models/caged/cg_spkrelv01.mdl
models/caged/cg_spkrwire01.mdl
models/caged/cg_spkrwire03.mdl
models/caged/cg_spkrwire04.mdl
models/caged/cg_spkrwire_b_01.mdl
models/caged/cg_spkrwire_d_01.mdl
models/caged/cg_spkrwire_d_03.mdl
models/caged/cg_vat_button01.mdl
models/caged/cg_vatsh01.mdl
models/caged/cg_vatswire01.mdl
models/caged/cg_ventgibs.mdl
models/caged/cg_vhs01.mdl
models/caged/cg_vhs03.mdl
models/caged/cg_vhsmulti01.mdl
models/caged/cg_wbundle01.mdl
models/caged/cg_wbundle02.mdl
models/caged/cg_wires01.mdl
models/caged/fleshgibs.mdl
models/caged/p_crowbar.mdl
models/caged/v_357.mdl
models/caged/v_9mmar.mdl
models/caged/v_9mmhandgun.mdl
models/caged/v_crossbow.mdl
models/caged/v_crowbar.mdl
models/caged/v_grenade.mdl
models/caged/v_m16a2.mdl
models/caged/v_medkit.mdl
models/caged/v_rpg.mdl
models/caged/v_satchel.mdl
models/caged/v_satchel_radio.mdl
models/caged/v_shotgun.mdl
models/caged/v_tripmine.mdl
models/caged/w_battery.mdl
models/caged/w_crowbar.mdl
models/caged/w_med_wall.mdl
models/caged/woodgibs.mdl
sound/caged/ambience/cg_achtext01.wav
sound/caged/ambience/cg_airflow01.wav
sound/caged/ambience/cg_alarm02.wav
sound/caged/ambience/cg_alarmbells01.wav
sound/caged/ambience/cg_amb02.wav
sound/caged/ambience/cg_amb03.wav
sound/caged/ambience/cg_amb04.wav
sound/caged/ambience/cg_amb05.wav
sound/caged/ambience/cg_amb07.wav
sound/caged/ambience/cg_amb09.wav
sound/caged/ambience/cg_amb_w_01.wav
sound/caged/ambience/cg_amb_w_02.wav
sound/caged/ambience/cg_amb_w_03b.wav
sound/caged/ambience/cg_basshum01.wav
sound/caged/ambience/cg_comopen01.wav
sound/caged/ambience/cg_field01.wav
sound/caged/ambience/cg_fridge01.wav
sound/caged/ambience/cg_groan_os02.wav
sound/caged/ambience/cg_groan_os03.wav
sound/caged/ambience/cg_groan_os04.wav
sound/caged/ambience/cg_groan_os05.wav
sound/caged/ambience/cg_groan_os06.wav
sound/caged/ambience/cg_hrm01.wav
sound/caged/ambience/cg_hrm02.wav
sound/caged/ambience/cg_radio01.wav
sound/caged/ambience/cg_rat01.wav
sound/caged/ambience/cg_riothum01.wav
sound/caged/ambience/cg_server01.wav
sound/caged/ambience/cg_sidedoor01.wav
sound/caged/ambience/cg_sign01.wav
sound/caged/ambience/cg_turhum01.wav
sound/caged/ambience/cg_turhum02.wav
sound/caged/ambience/cg_txt01.wav
sound/caged/ambience/cg_vat_think.wav
sound/caged/apache/ap_rotor2.wav
sound/caged/barney/ba_dontmake.wav
sound/caged/barney/ba_somuch.wav
sound/caged/barney/c1a2_ba_climb.wav
sound/caged/boid/boid_alert1.wav
sound/caged/boid/boid_alert2.wav
sound/caged/boid/boid_idle1.wav
sound/caged/boid/boid_idle2.wav
sound/caged/boid/boid_idle3.wav
sound/caged/buttons/cag_latch.wav
sound/caged/buttons/latchlocked1.wav
sound/caged/buttons/latchlocked2.wav
sound/caged/buttons/latchunlocked1.wav
sound/caged/buttons/latchunlocked2.wav
sound/caged/caged_materials.txt
sound/caged/elevator/cg_elvator01.wav
sound/caged/elevator/cg_elvator02.wav
sound/caged/elevator/cg_elvator04.wav
sound/caged/hgrunt/freeman!.wav
sound/caged/hgrunt/freeman.wav
sound/caged/music/Caged03.mp3
sound/caged/music/Caged04.mp3
sound/caged/scientist/alientrick.wav
sound/caged/scientist/announcer.wav
sound/caged/scientist/bloodsample.wav
sound/caged/scientist/cascade.wav
sound/caged/scientist/cough.wav
sound/caged/scientist/dinner.wav
sound/caged/scientist/everseen.wav
sound/caged/scientist/freeman.wav
sound/caged/scientist/newhevsuit.wav
sound/caged/scientist/of1a6_sc01.wav
sound/caged/scientist/perfectday.wav
sound/caged/scientist/sneeze.wav
sound/caged/vats/cg_vats01.wav
sound/caged/vats/cg_vats02.wav
sound/caged/vats/cg_vats03.wav
sound/caged/vats/vats_beepboop.wav
sound/caged/vats/vats_chargeup.wav
sound/caged/vats/vats_scream.wav
sound/caged/vo/cg_vo2_banan.wav
sound/caged/vo/cg_vo4_riot2.wav
sound/caged/vo/cg_vo_bong01.wav
sound/caged/vo/cg_vo_bong03.wav
sound/caged/vo/cg_vo_ident.wav
sound/caged/vo/cg_vo_maintw.wav
sound/caged/vo/cg_vo_riotalrm.wav
sound/caged/vo/cg_vo_turoff.wav
sound/caged/vo/vo10_can_do_it.wav
sound/caged/vo/vo10_i_arrived.wav
sound/caged/vo/vo10_need_it.wav
sound/caged/vo/vo10_push_em.wav
sound/caged/vo/vo10_want_bad.wav
sound/caged/vo/vo10_you_want.wav
sound/caged/vo/vo11_good_too.wav
sound/caged/vo/vo11_purr.wav
sound/caged/vo/vo12_icom.wav
sound/caged/vo/vo4_anno_spam.wav
sound/caged/vo/vo4_badges.wav
sound/caged/vo/vo4_report_imed.wav
sound/caged/vo/vo4_reportdeath.wav
sound/caged/vo/vo4_soap_resup.wav
sound/caged/vo/vo4_tacoday.wav
sound/caged/vo/vo4_user_error.wav
sound/caged/vo/vo4_vend_sup.wav
sound/caged/vo/vo5_bongee_01.wav
sound/caged/vo/vo5_init_test.wav
sound/caged/vo/vo5_test1.wav
sound/caged/vo/vo5_test2.wav
sound/caged/vo/vo5_test3.wav
sound/caged/vo/vo6_are_lonely.wav
sound/caged/vo/vo6_auto_engage.wav
sound/caged/vo/vo6_be_friends.wav
sound/caged/vo/vo6_good_2u.wav
sound/caged/vo/vo6_hi_alltest.wav
sound/caged/vo/vo6_iam_lonely.wav
sound/caged/vo/vo6_leave_me.wav
sound/caged/vo/vo6_loveme.wav
sound/caged/vo/vo6_loveyou.wav
sound/caged/vo/vo6_make_life.wav
sound/caged/vo/vo6_more_friends.wav
sound/caged/vo/vo6_no_have.wav
sound/caged/vo/vo6_offer.wav
sound/caged/vo/vo6_offer2.wav
sound/caged/vo/vo6_where_go.wav
sound/caged/vo/vo6_would_stay.wav
sound/caged/vo/vo6_you_lonely.wav
sound/caged/vo/vo7_come_close.wav
sound/caged/vo/vo7_good_buttons.wav
sound/caged/vo/vo7_like_push.wav
sound/caged/vo/vo8_aah.wav
sound/caged/vo/vo8_ooh.wav
sound/caged/vo/vo8_ooh_baby.wav
sound/caged/vo/vo8_right_there.wav
sound/caged/vo/vo8_thats_it.wav
sound/caged/vo/vo8_yes.wav
sound/caged/vo/vo8_yes_yes.wav
sound/caged/vo/vo9_closer.wav
sound/caged/vo/vo9_come_on.wav
sound/caged/vo/vo9_on_closer.wav
sound/caged/vo/vo9_pushb.wav
sound/caged/vo/vo9_pushb2.wav
sound/caged/vo/vo9_pushb3.wav
sound/caged/weapons/cbar_hit1.wav
sound/caged/weapons/cbar_hit2.wav
sprites/caged/cg_comment01a.spr
sprites/caged/cg_vertflare01.spr
