// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

cg_caged.wad
cg_event.wad
cg_hl.wad
entity.wad
models/caged/agibs.mdl
models/caged/can.mdl
models/caged/cg_bucket02.mdl
models/caged/cg_bulb01.mdl
models/caged/cg_cardboard.mdl
models/caged/cg_cellspigot.mdl
models/caged/cg_hrebar01.mdl
models/caged/cg_meter01.mdl
models/caged/cg_nails01.mdl
models/caged/cg_nails02.mdl
models/caged/cg_pipegibs.mdl
models/caged/cg_pipelwr01.mdl
models/caged/cg_poo.mdl
models/caged/cg_ratgibs.mdl
models/caged/cg_spkrelv01.mdl
models/caged/cg_spkrwire01.mdl
models/caged/cg_ventbits.mdl
models/caged/cg_ventgibs.mdl
models/caged/cg_wfloor01.mdl
models/caged/cg_wires01.mdl
models/caged/cg_wires02.mdl
models/caged/cg_wroom01.mdl
models/caged/fleshgibs.mdl
models/caged/p_crowbar.mdl
models/caged/v_357.mdl
models/caged/v_9mmar.mdl
models/caged/v_9mmhandgun.mdl
models/caged/v_crossbow.mdl
models/caged/v_crowbar.mdl
models/caged/v_grenade.mdl
models/caged/v_m16a2.mdl
models/caged/v_medkit.mdl
models/caged/v_rpg.mdl
models/caged/v_satchel.mdl
models/caged/v_satchel_radio.mdl
models/caged/v_shotgun.mdl
models/caged/v_tripmine.mdl
models/caged/w_battery.mdl
models/caged/w_crowbar.mdl
models/caged/woodgibs.mdl
sound/caged/ambience/cag_pain1.wav
sound/caged/ambience/cag_pain5.wav
sound/caged/ambience/cag_shit_dn.wav
sound/caged/ambience/cag_steam01.wav
sound/caged/ambience/cg_achtext01.wav
sound/caged/ambience/cg_airflow01.wav
sound/caged/ambience/cg_amb01.wav
sound/caged/ambience/cg_amb02.wav
sound/caged/ambience/cg_amb03.wav
sound/caged/ambience/cg_amb04.wav
sound/caged/ambience/cg_amb05.wav
sound/caged/ambience/cg_amb07.wav
sound/caged/ambience/cg_amb_w_01.wav
sound/caged/ambience/cg_amb_w_02.wav
sound/caged/ambience/cg_amb_w_03b.wav
sound/caged/ambience/cg_basshum01.wav
sound/caged/ambience/cg_bonalarm01.wav
sound/caged/ambience/cg_boxfloat01.wav
sound/caged/ambience/cg_boxfloat02.wav
sound/caged/ambience/cg_clang02.wav
sound/caged/ambience/cg_comopen01.wav
sound/caged/ambience/cg_doorbang01.wav
sound/caged/ambience/cg_doorbang02.wav
sound/caged/ambience/cg_doorbang03.wav
sound/caged/ambience/cg_doorbang04.wav
sound/caged/ambience/cg_field01.wav
sound/caged/ambience/cg_groan_os01.wav
sound/caged/ambience/cg_groan_os02.wav
sound/caged/ambience/cg_groan_os04.wav
sound/caged/ambience/cg_groan_os06.wav
sound/caged/ambience/cg_hg_elim01.wav
sound/caged/ambience/cg_lswitch01.wav
sound/caged/ambience/cg_pbulge01.wav
sound/caged/ambience/cg_pgroan01.wav
sound/caged/ambience/cg_pgroan02.wav
sound/caged/ambience/cg_pipestress01.wav
sound/caged/ambience/cg_pumpoff01.wav
sound/caged/ambience/cg_rat01.wav
sound/caged/ambience/cg_scuffle01.wav
sound/caged/ambience/cg_scuffle02.wav
sound/caged/ambience/cg_txt01.wav
sound/caged/ambience/cg_wateron01.wav
sound/caged/ambience/cg_watersplash01.wav
sound/caged/apache/ap_rotor2.wav
sound/caged/barney/ba_dontmake.wav
sound/caged/barney/ba_somuch.wav
sound/caged/barney/c1a2_ba_climb.wav
sound/caged/boid/boid_alert1.wav
sound/caged/boid/boid_alert2.wav
sound/caged/boid/boid_idle1.wav
sound/caged/boid/boid_idle2.wav
sound/caged/boid/boid_idle3.wav
sound/caged/buttons/cag_latch.wav
sound/caged/buttons/latchlocked1.wav
sound/caged/buttons/latchlocked2.wav
sound/caged/buttons/latchunlocked1.wav
sound/caged/buttons/latchunlocked2.wav
sound/caged/caged_materials.txt
sound/caged/hgrunt/freeman!.wav
sound/caged/hgrunt/freeman.wav
sound/caged/music/Caged02.mp3
sound/caged/music/Caged03.mp3
sound/caged/music/Caged04.mp3
sound/caged/scientist/alientrick.wav
sound/caged/scientist/announcer.wav
sound/caged/scientist/bloodsample.wav
sound/caged/scientist/cascade.wav
sound/caged/scientist/cough.wav
sound/caged/scientist/dinner.wav
sound/caged/scientist/everseen.wav
sound/caged/scientist/freeman.wav
sound/caged/scientist/newhevsuit.wav
sound/caged/scientist/of1a6_sc01.wav
sound/caged/scientist/perfectday.wav
sound/caged/scientist/sneeze.wav
sound/caged/vo/cg_vo3_cust2.wav
sound/caged/vo/cg_vo3_paci2.wav
sound/caged/vo/cg_vo_bong01.wav
sound/caged/vo/cg_vo_bong03.wav
sound/caged/vo/cg_vo_comterms.wav
sound/caged/vo/cg_vo_earlytrm.wav
sound/caged/vo/cg_vo_gruelrprt.wav
sound/caged/vo/cg_vo_time00.wav
sound/caged/vo/cg_vo_time55.wav
sound/caged/vo/cg_vo_trmtkplc.wav
sound/caged/vo/cg_vo_vioactiv.wav
sound/caged/vo/vo13_nuke01.wav
sound/caged/vo/vo14_subtb0.wav
sound/caged/vo/vo14_subtb1.wav
sound/caged/vo/vo14_subtb2.wav
sound/caged/vo/vo14_subtb3.wav
sound/caged/vo/vo14_subtb4.wav
sound/caged/vo/vo14_subtb5.wav
sound/caged/vo/vo14_subtur4.wav
sound/caged/weapons/cbar_hit1.wav
sound/caged/weapons/cbar_hit2.wav
sprites/caged/cg_comment01a.spr
sprites/caged/cg_spray01.spr
sprites/caged/cg_vertflare01.spr
