// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

cg_caged.wad
cg_hl.wad
entity.wad
models/caged/agibs.mdl
models/caged/can.mdl
models/caged/can2.mdl
models/caged/cg_bulb01.mdl
models/caged/cg_flare01.mdl
models/caged/cg_flare02.mdl
models/caged/cg_flare03.mdl
models/caged/cg_flare04.mdl
models/caged/cg_spkrwire_d_01.mdl
models/caged/cg_wires01.mdl
models/caged/fleshgibs.mdl
models/caged/p_crowbar.mdl
models/caged/v_357.mdl
models/caged/v_9mmar.mdl
models/caged/v_9mmhandgun.mdl
models/caged/v_crossbow.mdl
models/caged/v_crowbar.mdl
models/caged/v_grenade.mdl
models/caged/v_m16a2.mdl
models/caged/v_medkit.mdl
models/caged/v_rpg.mdl
models/caged/v_satchel.mdl
models/caged/v_satchel_radio.mdl
models/caged/v_shotgun.mdl
models/caged/v_tripmine.mdl
models/caged/w_battery.mdl
models/caged/w_crowbar.mdl
models/caged/woodgibs.mdl
sound/caged/ambience/cg_achtext01.wav
sound/caged/ambience/cg_alarmbells01.wav
sound/caged/ambience/cg_amb01.wav
sound/caged/ambience/cg_amb04.wav
sound/caged/ambience/cg_amb08.wav
sound/caged/ambience/cg_amb_w_01.wav
sound/caged/ambience/cg_fridge01.wav
sound/caged/ambience/cg_woosh1.wav
sound/caged/apache/ap_rotor2.wav
sound/caged/barney/ba_dontmake.wav
sound/caged/barney/ba_somuch.wav
sound/caged/barney/bar_step1.wav
sound/caged/barney/bar_step3.wav
sound/caged/barney/c1a2_ba_climb.wav
sound/caged/boid/boid_alert1.wav
sound/caged/boid/boid_alert2.wav
sound/caged/boid/boid_idle1.wav
sound/caged/boid/boid_idle2.wav
sound/caged/boid/boid_idle3.wav
sound/caged/buttons/latchlocked1.wav
sound/caged/buttons/latchlocked2.wav
sound/caged/buttons/latchunlocked1.wav
sound/caged/buttons/latchunlocked2.wav
sound/caged/caged_materials.txt
sound/caged/hgrunt/freeman!.wav
sound/caged/hgrunt/freeman.wav
sound/caged/music/Caged04.mp3
sound/caged/music/Caged07.mp3
sound/caged/music/Caged08.mp3
sound/caged/scientist/alientrick.wav
sound/caged/scientist/announcer.wav
sound/caged/scientist/bloodsample.wav
sound/caged/scientist/cascade.wav
sound/caged/scientist/cough.wav
sound/caged/scientist/dinner.wav
sound/caged/scientist/everseen.wav
sound/caged/scientist/freeman.wav
sound/caged/scientist/newhevsuit.wav
sound/caged/scientist/of1a6_sc01.wav
sound/caged/scientist/perfectday.wav
sound/caged/scientist/sneeze.wav
sound/caged/weapons/cbar_hit1.wav
sound/caged/weapons/cbar_hit2.wav
sprites/caged/cg_nuke01.spr
sprites/caged/cg_splash01.spr
sprites/caged/cg_vertflare01.spr
