// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

cg_caged.wad
cg_hl.wad
entity.wad
gfx/env/grimmnightbk.tga
gfx/env/grimmnightdn.tga
gfx/env/grimmnightft.tga
gfx/env/grimmnightlf.tga
gfx/env/grimmnightrt.tga
gfx/env/grimmnightup.tga
models/caged/agibs.mdl
models/caged/can.mdl
models/caged/can2.mdl
models/caged/cg_bns_jreel04.mdl
models/caged/cg_bns_jreel05.mdl
models/caged/cg_bns_wire01.mdl
models/caged/cg_bns_wire02.mdl
models/caged/cg_bulb01.mdl
models/caged/cg_buzzwire01.mdl
models/caged/cg_can02.mdl
models/caged/cg_kioskwire01.mdl
models/caged/cg_reels05.mdl
models/caged/cg_reels06.mdl
models/caged/cg_reels07.mdl
models/caged/cg_spkrelv01.mdl
models/caged/cg_spkrwire_b_01.mdl
models/caged/cg_spkrwire_d_02.mdl
models/caged/fleshgibs.mdl
models/caged/p_crowbar.mdl
models/caged/v_357.mdl
models/caged/v_9mmar.mdl
models/caged/v_9mmhandgun.mdl
models/caged/v_crossbow.mdl
models/caged/v_crowbar.mdl
models/caged/v_grenade.mdl
models/caged/v_m16a2.mdl
models/caged/v_medkit.mdl
models/caged/v_rpg.mdl
models/caged/v_satchel.mdl
models/caged/v_satchel_radio.mdl
models/caged/v_shotgun.mdl
models/caged/v_tripmine.mdl
models/caged/w_battery.mdl
models/caged/w_crowbar.mdl
models/caged/woodgibs.mdl
sound/caged/ambience/cg_airflow01.wav
sound/caged/ambience/cg_amb01.wav
sound/caged/ambience/cg_amb02.wav
sound/caged/ambience/cg_amb07.wav
sound/caged/ambience/cg_amb09.wav
sound/caged/ambience/cg_amb_w_01.wav
sound/caged/ambience/cg_basshum01.wav
sound/caged/ambience/cg_blips1.wav
sound/caged/ambience/cg_bonalarm01.wav
sound/caged/ambience/cg_combuzz01.wav
sound/caged/ambience/cg_comopen01.wav
sound/caged/ambience/cg_field02.wav
sound/caged/ambience/cg_fridge01.wav
sound/caged/ambience/cg_grinder01.wav
sound/caged/ambience/cg_grinder02.wav
sound/caged/ambience/cg_riothum01.wav
sound/caged/ambience/cg_sign01.wav
sound/caged/ambience/cg_turhum01.wav
sound/caged/ambience/cg_turhum02.wav
sound/caged/ambience/cg_turhum03.wav
sound/caged/ambience/cg_turhum04.wav
sound/caged/ambience/cg_txt01.wav
sound/caged/apache/ap_rotor2.wav
sound/caged/barney/ba_dontmake.wav
sound/caged/barney/ba_somuch.wav
sound/caged/barney/bar_step1.wav
sound/caged/barney/bar_step3.wav
sound/caged/barney/c1a2_ba_climb.wav
sound/caged/boid/boid_alert1.wav
sound/caged/boid/boid_alert2.wav
sound/caged/boid/boid_idle1.wav
sound/caged/boid/boid_idle2.wav
sound/caged/boid/boid_idle3.wav
sound/caged/bonus/cg_bns2_jdg01.wav
sound/caged/bonus/cg_bns2_jdg02.wav
sound/caged/bonus/cg_bns2_jdg03.wav
sound/caged/bonus/cg_bns2_jdg04.wav
sound/caged/bonus/cg_bns2_jdg05.wav
sound/caged/bonus/cg_bns3_vox01.wav
sound/caged/bonus/cg_bns3_vox02.wav
sound/caged/bonus/cg_bns3_vox03.wav
sound/caged/bonus/cg_bns4_jdg01.wav
sound/caged/bonus/cg_bns4_jdg03.wav
sound/caged/bonus/cg_bns4_jdg05.wav
sound/caged/bonus/cg_bns4_jdg07.wav
sound/caged/bonus/cg_bns4_jdg08.wav
sound/caged/bonus/cg_bns_amb01.wav
sound/caged/bonus/cg_bns_amb02.wav
sound/caged/bonus/cg_bns_conv01.wav
sound/caged/bonus/cg_bns_conv02.wav
sound/caged/bonus/cg_bns_exdoor01.wav
sound/caged/bonus/cg_bns_flaps01.wav
sound/caged/bonus/cg_bns_hum01.wav
sound/caged/bonus/cg_bns_icom01.wav
sound/caged/bonus/cg_bns_jdg01.wav
sound/caged/bonus/cg_bns_jdg02.wav
sound/caged/bonus/cg_bns_jdg03.wav
sound/caged/bonus/cg_bns_jdg04.wav
sound/caged/bonus/cg_bns_jdg05.wav
sound/caged/bonus/cg_bns_jdg06.wav
sound/caged/bonus/cg_bns_jdg07.wav
sound/caged/bonus/cg_bns_jdg08.wav
sound/caged/bonus/cg_bns_jdg09.wav
sound/caged/bonus/cg_bns_jdg10.wav
sound/caged/bonus/cg_bns_jdg11.wav
sound/caged/bonus/cg_bns_jdg12.wav
sound/caged/bonus/cg_bns_jdg13.wav
sound/caged/bonus/cg_bns_jdg14.wav
sound/caged/bonus/cg_bns_jdg15.wav
sound/caged/bonus/cg_bns_jdg16.wav
sound/caged/bonus/cg_bns_jdg17.wav
sound/caged/bonus/cg_bns_jdg18.wav
sound/caged/bonus/cg_bns_jdg19.wav
sound/caged/bonus/cg_bns_jdg20.wav
sound/caged/bonus/cg_bns_jdg21.wav
sound/caged/bonus/cg_bns_jdg22.wav
sound/caged/bonus/cg_bns_jdg23.wav
sound/caged/bonus/cg_bns_jdg24.wav
sound/caged/bonus/cg_bns_jstr01.wav
sound/caged/bonus/cg_bns_lift01.wav
sound/caged/bonus/cg_bns_lift02.wav
sound/caged/bonus/cg_bns_lzr01.wav
sound/caged/bonus/cg_bns_lzr02.wav
sound/caged/bonus/cg_bns_lzr03.wav
sound/caged/bonus/cg_bns_lzr04.wav
sound/caged/bonus/cg_bns_lzr05.wav
sound/caged/bonus/cg_bns_lzr06.wav
sound/caged/bonus/cg_bns_not01.wav
sound/caged/bonus/cg_bns_pp00.wav
sound/caged/bonus/cg_bns_pp02.wav
sound/caged/bonus/cg_bns_pwin00.wav
sound/caged/bonus/cg_bns_pwin02.wav
sound/caged/bonus/cg_bns_sdoor01.wav
sound/caged/bonus/cg_bns_sdoor02.wav
sound/caged/bonus/cg_bns_sel01.wav
sound/caged/bonus/cg_bns_sel02.wav
sound/caged/bonus/cg_bns_stm01.wav
sound/caged/bonus/cg_bns_switch01.wav
sound/caged/bonus/cg_bns_switch02.wav
sound/caged/bonus/cg_bns_vox01.wav
sound/caged/bonus/cg_bns_vox02.wav
sound/caged/bonus/cg_bns_vox03.wav
sound/caged/bonus/cg_bns_vox04.wav
sound/caged/bonus/cg_bns_vox05.wav
sound/caged/bonus/cg_bns_vox06.wav
sound/caged/bonus/cg_bns_vox07.wav
sound/caged/bonus/cg_bns_vox08.wav
sound/caged/bonus/cg_brd_flash1.wav
sound/caged/bonus/cg_brd_flash2.wav
sound/caged/bonus/cg_brd_flash3.wav
sound/caged/bonus/cg_brd_flash4.wav
sound/caged/bonus/cg_neon_on01.wav
sound/caged/bonus/cg_neon_sel1.wav
sound/caged/bonus/cg_neon_sel2.wav
sound/caged/bonus/cg_neon_sel3.wav
sound/caged/buttons/cg_button_b01.wav
sound/caged/buttons/cg_button_no.wav
sound/caged/buttons/cg_button_yes.wav
sound/caged/buttons/latchlocked1.wav
sound/caged/buttons/latchlocked2.wav
sound/caged/buttons/latchunlocked1.wav
sound/caged/buttons/latchunlocked2.wav
sound/caged/caged_materials.txt
sound/caged/elevator/cg_elvator02.wav
sound/caged/elevator/cg_elvator03.wav
sound/caged/elevator/cg_elvator04.wav
sound/caged/elevator/cg_elvator05.wav
sound/caged/hgrunt/freeman!.wav
sound/caged/hgrunt/freeman.wav
sound/caged/music/Caged09.mp3
sound/caged/scientist/alientrick.wav
sound/caged/scientist/announcer.wav
sound/caged/scientist/bloodsample.wav
sound/caged/scientist/cascade.wav
sound/caged/scientist/cough.wav
sound/caged/scientist/dinner.wav
sound/caged/scientist/everseen.wav
sound/caged/scientist/freeman.wav
sound/caged/scientist/newhevsuit.wav
sound/caged/scientist/of1a6_sc01.wav
sound/caged/scientist/perfectday.wav
sound/caged/scientist/sneeze.wav
sound/caged/vo/cg_vo2_bongelv.wav
sound/caged/vo/cg_vo_bong01.wav
sound/caged/vo/cg_vo_earlytrm.wav
sound/caged/vo/vo4_badges.wav
sound/caged/vo/vo4_report_imed.wav
sound/caged/vo/vo5_bongee_01.wav
sound/caged/weapons/cbar_hit1.wav
sound/caged/weapons/cbar_hit2.wav
sprites/caged/cg_vertflare01.spr
