// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

cg_caged.wad
cg_hl.wad
entity.wad
gfx/env/grimmnightbk.tga
gfx/env/grimmnightdn.tga
gfx/env/grimmnightft.tga
gfx/env/grimmnightlf.tga
gfx/env/grimmnightrt.tga
gfx/env/grimmnightup.tga
models/caged/agibs.mdl
models/caged/can.mdl
models/caged/can2.mdl
models/caged/cg_can02.mdl
models/caged/cg_cardboard.mdl
models/caged/cg_flare01.mdl
models/caged/cg_flare02.mdl
models/caged/cg_flarec3_01.mdl
models/caged/cg_hallwire02.mdl
models/caged/cg_ladder01.mdl
models/caged/cg_manhole.mdl
models/caged/cg_palm04.mdl
models/caged/cg_palm05.mdl
models/caged/cg_palm06.mdl
models/caged/cg_palm07.mdl
models/caged/cg_palm09.mdl
models/caged/cg_pier01.mdl
models/caged/cg_rpg_a.mdl
models/caged/cg_soap02.mdl
models/caged/cg_spkrwire_d_02.mdl
models/caged/cg_spkrwire_d_03.mdl
models/caged/cg_ventgibs.mdl
models/caged/fleshgibs.mdl
models/caged/p_crowbar.mdl
models/caged/v_357.mdl
models/caged/v_9mmar.mdl
models/caged/v_9mmhandgun.mdl
models/caged/v_crossbow.mdl
models/caged/v_crowbar.mdl
models/caged/v_grenade.mdl
models/caged/v_m16a2.mdl
models/caged/v_medkit.mdl
models/caged/v_rpg.mdl
models/caged/v_satchel.mdl
models/caged/v_satchel_radio.mdl
models/caged/v_shotgun.mdl
models/caged/v_tripmine.mdl
models/caged/w_battery.mdl
models/caged/w_crowbar.mdl
models/caged/w_med_wall.mdl
models/caged/woodgibs.mdl
sound/caged/ambience/cg_alarmbells01.wav
sound/caged/ambience/cg_amb03.wav
sound/caged/ambience/cg_amb04.wav
sound/caged/ambience/cg_amb07.wav
sound/caged/ambience/cg_amb08.wav
sound/caged/ambience/cg_basshum01.wav
sound/caged/ambience/cg_boateng_01.wav
sound/caged/ambience/cg_comopen01.wav
sound/caged/ambience/cg_doorspray.wav
sound/caged/ambience/cg_doortalk01.wav
sound/caged/ambience/cg_dscrape01.wav
sound/caged/ambience/cg_dscrape02.wav
sound/caged/ambience/cg_escsiren01.wav
sound/caged/ambience/cg_flare01.wav
sound/caged/ambience/cg_groan_os01.wav
sound/caged/ambience/cg_groan_os04.wav
sound/caged/ambience/cg_nukealarm01.wav
sound/caged/ambience/cg_nukeblast01.wav
sound/caged/ambience/cg_nukeblast02.wav
sound/caged/ambience/cg_seawaves01.wav
sound/caged/ambience/cg_slurry01.wav
sound/caged/ambience/cg_txt01.wav
sound/caged/ambience/cg_winopen01.wav
sound/caged/apache/ap_rotor2.wav
sound/caged/barney/ba_dontmake.wav
sound/caged/barney/ba_somuch.wav
sound/caged/barney/c1a2_ba_climb.wav
sound/caged/boid/boid_alert1.wav
sound/caged/boid/boid_alert2.wav
sound/caged/boid/boid_idle1.wav
sound/caged/boid/boid_idle2.wav
sound/caged/boid/boid_idle3.wav
sound/caged/buttons/cag_latch.wav
sound/caged/buttons/latchlocked1.wav
sound/caged/buttons/latchlocked2.wav
sound/caged/buttons/latchunlocked1.wav
sound/caged/buttons/latchunlocked2.wav
sound/caged/caged_materials.txt
sound/caged/hgrunt/freeman!.wav
sound/caged/hgrunt/freeman.wav
sound/caged/music/Caged05.mp3
sound/caged/music/Caged06.mp3
sound/caged/scientist/alientrick.wav
sound/caged/scientist/announcer.wav
sound/caged/scientist/bloodsample.wav
sound/caged/scientist/cascade.wav
sound/caged/scientist/cough.wav
sound/caged/scientist/dinner.wav
sound/caged/scientist/everseen.wav
sound/caged/scientist/freeman.wav
sound/caged/scientist/newhevsuit.wav
sound/caged/scientist/of1a6_sc01.wav
sound/caged/scientist/perfectday.wav
sound/caged/scientist/sneeze.wav
sound/caged/vo/cg_vo2_n_00.wav
sound/caged/vo/cg_vo2_n_01.wav
sound/caged/vo/cg_vo2_n_02.wav
sound/caged/vo/cg_vo2_n_03.wav
sound/caged/vo/cg_vo2_n_04.wav
sound/caged/vo/cg_vo2_n_05.wav
sound/caged/vo/cg_vo2_n_06.wav
sound/caged/vo/cg_vo2_n_07.wav
sound/caged/vo/cg_vo2_n_08.wav
sound/caged/vo/cg_vo2_n_09.wav
sound/caged/vo/cg_vo2_n_10.wav
sound/caged/vo/cg_vo2_n_half.wav
sound/caged/vo/cg_vo2_n_quart.wav
sound/caged/vo/cg_vo2_nuclear1.wav
sound/caged/vo/cg_vo2_window.wav
sound/caged/vo/cg_vo_bong01.wav
sound/caged/vo/vo13_nuke03.wav
sound/caged/weapons/cbar_hit1.wav
sound/caged/weapons/cbar_hit2.wav
sprites/caged/cg_flare01.spr
sprites/caged/cg_vertflare01.spr
