// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

cg_caged.wad
cg_hl.wad
entity.wad
gfx/env/grimmnightbk.tga
gfx/env/grimmnightdn.tga
gfx/env/grimmnightft.tga
gfx/env/grimmnightlf.tga
gfx/env/grimmnightrt.tga
gfx/env/grimmnightup.tga
models/caged/agibs.mdl
models/caged/can.mdl
models/caged/can2.mdl
models/caged/cg_bnan.mdl
models/caged/cg_boomgibs.mdl
models/caged/cg_bucket01.mdl
models/caged/cg_bulb01.mdl
models/caged/cg_can02.mdl
models/caged/cg_cardboard.mdl
models/caged/cg_cbar_prop.mdl
models/caged/cg_cbar_propt.mdl
models/caged/cg_flare03.mdl
models/caged/cg_flare04.mdl
models/caged/cg_oldcan01.mdl
models/caged/cg_palm02.mdl
models/caged/cg_palm04.mdl
models/caged/cg_palm06.mdl
models/caged/cg_quarter01.mdl
models/caged/cg_ratgibs.mdl
models/caged/cg_shower02.mdl
models/caged/cg_soap01.mdl
models/caged/cg_spkrelv01.mdl
models/caged/cg_spkrwire_b_01.mdl
models/caged/cg_spkrwire_b_02.mdl
models/caged/cg_spkrwire_d_01.mdl
models/caged/cg_spkrwire_d_02.mdl
models/caged/cg_vendbits01.mdl
models/caged/cg_ventgibs.mdl
models/caged/cg_wires02.mdl
models/caged/cg_yelmetgibs.mdl
models/caged/fleshgibs.mdl
models/caged/p_crowbar.mdl
models/caged/v_357.mdl
models/caged/v_9mmar.mdl
models/caged/v_9mmhandgun.mdl
models/caged/v_crossbow.mdl
models/caged/v_crowbar.mdl
models/caged/v_grenade.mdl
models/caged/v_m16a2.mdl
models/caged/v_medkit.mdl
models/caged/v_rpg.mdl
models/caged/v_satchel.mdl
models/caged/v_satchel_radio.mdl
models/caged/v_shotgun.mdl
models/caged/v_tripmine.mdl
models/caged/w_battery.mdl
models/caged/w_crowbar.mdl
models/caged/w_med_wall.mdl
models/caged/woodgibs.mdl
sound/caged/ambience/cg_achtext01.wav
sound/caged/ambience/cg_airflow01.wav
sound/caged/ambience/cg_alarmbells01.wav
sound/caged/ambience/cg_amb01.wav
sound/caged/ambience/cg_amb02.wav
sound/caged/ambience/cg_amb03.wav
sound/caged/ambience/cg_amb04.wav
sound/caged/ambience/cg_amb08.wav
sound/caged/ambience/cg_amb09.wav
sound/caged/ambience/cg_amb11.wav
sound/caged/ambience/cg_amb_w_01.wav
sound/caged/ambience/cg_amb_w_02.wav
sound/caged/ambience/cg_basshum01.wav
sound/caged/ambience/cg_blips1.wav
sound/caged/ambience/cg_blips2.wav
sound/caged/ambience/cg_ccans01.wav
sound/caged/ambience/cg_cdoor01.wav
sound/caged/ambience/cg_cellopen01.wav
sound/caged/ambience/cg_comopen01.wav
sound/caged/ambience/cg_field01.wav
sound/caged/ambience/cg_flare01.wav
sound/caged/ambience/cg_fridge01.wav
sound/caged/ambience/cg_radio01.wav
sound/caged/ambience/cg_rappel01.wav
sound/caged/ambience/cg_rat01.wav
sound/caged/ambience/cg_seagull01.wav
sound/caged/ambience/cg_sign01.wav
sound/caged/ambience/cg_slurry01.wav
sound/caged/ambience/cg_txt01.wav
sound/caged/apache/ap_rotor2.wav
sound/caged/barney/ba_dontmake.wav
sound/caged/barney/ba_somuch.wav
sound/caged/barney/c1a2_ba_climb.wav
sound/caged/boid/boid_alert1.wav
sound/caged/boid/boid_alert2.wav
sound/caged/boid/boid_idle1.wav
sound/caged/boid/boid_idle2.wav
sound/caged/boid/boid_idle3.wav
sound/caged/buttons/cag_latch.wav
sound/caged/buttons/latchlocked1.wav
sound/caged/buttons/latchlocked2.wav
sound/caged/buttons/latchunlocked1.wav
sound/caged/buttons/latchunlocked2.wav
sound/caged/caged_materials.txt
sound/caged/elevator/cg_elvator02.wav
sound/caged/elevator/cg_elvator03.wav
sound/caged/elevator/cg_elvator04.wav
sound/caged/hgrunt/freeman!.wav
sound/caged/hgrunt/freeman.wav
sound/caged/music/Caged03.mp3
sound/caged/scientist/alientrick.wav
sound/caged/scientist/announcer.wav
sound/caged/scientist/bloodsample.wav
sound/caged/scientist/cascade.wav
sound/caged/scientist/cough.wav
sound/caged/scientist/dinner.wav
sound/caged/scientist/everseen.wav
sound/caged/scientist/freeman.wav
sound/caged/scientist/newhevsuit.wav
sound/caged/scientist/of1a6_sc01.wav
sound/caged/scientist/perfectday.wav
sound/caged/scientist/sneeze.wav
sound/caged/vo/cg_vo2_bongelv.wav
sound/caged/vo/cg_vo2_contmob.wav
sound/caged/vo/cg_vo2_exercise.wav
sound/caged/vo/cg_vo2_exitop2.wav
sound/caged/vo/cg_vo2_gruel.wav
sound/caged/vo/cg_vo2_maintelv.wav
sound/caged/vo/cg_vo2_rodent.wav
sound/caged/vo/cg_vo2_vending.wav
sound/caged/vo/cg_vo_bong01.wav
sound/caged/vo/cg_vo_gruelrprt.wav
sound/caged/weapons/cbar_hit1.wav
sound/caged/weapons/cbar_hit2.wav
sprites/caged/cg_comment01a.spr
sprites/caged/cg_flare01.spr
sprites/caged/cg_vertflare01.spr
