// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/doombk.tga
gfx/env/doomdn.tga
gfx/env/doomft.tga
gfx/env/doomlf.tga
gfx/env/doomrt.tga
gfx/env/doomup.tga
models/classic/controller.mdl
models/classic/controllerT.mdl
models/classic/imp.mdl
models/classic/imp01.mdl
models/classic/imp02.mdl
models/classic/impT.mdl
models/classic/islave.mdl
models/classic/p_9mmar.mdl
models/classic/p_egon.mdl
models/classic/p_rpg.mdl
models/classic/p_shotgun.mdl
models/classic/pinky.mdl
models/classic/pinky01.mdl
models/classic/pinkyT.mdl
models/classic/spiderdemon.mdl
models/classic/spiderdemonT.mdl
models/classic/v_9mmAR.mdl
models/classic/v_9mmhandgun.mdl
models/classic/v_crowbar.mdl
models/classic/v_egon.mdl
models/classic/v_rpg.mdl
models/classic/v_shotgun.mdl
models/classic/w_battery.mdl
models/classic/w_batteryT.mdl
models/classic/w_crowbar.mdl
models/classic/w_crowbarT.mdl
models/classic/w_egon.mdl
models/classic/w_egonT.mdl
models/classic/w_medkit.mdl
models/classic/w_medkitT.mdl
models/classic/w_minigun.mdl
models/classic/w_rpg.mdl
models/classic/w_rpgT.mdl
models/classic/w_shotgun.mdl
models/classic/w_shotgunT.mdl
models/classic/zombieman_dark.mdl
models/classic/zombieman_darkT.mdl
models/classic/zombieman_white.mdl
models/classic/zombieman_whiteT.mdl
sound/classic/Baron/slv_alert1.WAV
sound/classic/Baron/slv_alert3.WAV
sound/classic/Baron/slv_alert4.WAV
sound/classic/Baron/slv_die1.WAV
sound/classic/Baron/slv_die2.WAV
sound/classic/Baron/slv_pain1.wav
sound/classic/Baron/slv_pain2.wav
sound/classic/Baron/slv_word1.WAV
sound/classic/Baron/slv_word2.WAV
sound/classic/Baron/slv_word3.WAV
sound/classic/Baron/slv_word4.WAV
sound/classic/Baron/slv_word5.WAV
sound/classic/Baron/slv_word6.WAV
sound/classic/Baron/slv_word7.WAV
sound/classic/Baron/slv_word8.WAV
sound/classic/BGMUSIC01.wav
sound/classic/BGMUSIC02.wav
sound/classic/BGMUSIC03.wav
sound/classic/BGMUSIC04.wav
sound/classic/BGMUSIC05.wav
sound/classic/BGMUSIC06.wav
sound/classic/BGMUSIC08.wav
sound/classic/BGMUSIC09.wav
sound/classic/BGMUSIC12.wav
sound/classic/Buttons/DSSWTCHN.wav
sound/classic/Buttons/ENDBUTTON.wav
sound/classic/DOOM.wav
sound/classic/Doors/doormove1.wav
sound/classic/Doors/doormove2.WAV
sound/classic/Doors/doorstop1.WAV
sound/classic/Doors/doorstop2.WAV
sound/classic/DSPDEMON.WAV
sound/classic/DSPTELEPORT.wav
sound/classic/Imp/claw_strike1.WAV
sound/classic/Imp/claw_strike2.WAV
sound/classic/Imp/claw_strike3.WAV
sound/classic/Imp/slv_alert1.WAV
sound/classic/Imp/slv_alert3.WAV
sound/classic/Imp/slv_alert4.WAV
sound/classic/Imp/slv_die1.WAV
sound/classic/Imp/slv_die2.WAV
sound/classic/Imp/slv_pain1.WAV
sound/classic/Imp/slv_pain2.WAV
sound/classic/Items/9mmclip1.wav
sound/classic/Items/gunpickup2.wav
sound/classic/Items/smallmedkit1.WAV
sound/classic/Pinky/bc_attackgrowl.wav
sound/classic/Pinky/bc_attackgrowl2.wav
sound/classic/Pinky/bc_attackgrowl3.WAV
sound/classic/Pinky/bc_die1.wav
sound/classic/Pinky/bc_die2.wav
sound/classic/Pinky/bc_die3.wav
sound/classic/Pinky/bc_idle1.wav
sound/classic/Pinky/bc_idle2.wav
sound/classic/Pinky/bc_idle3.wav
sound/classic/Pinky/bc_idle4.wav
sound/classic/Pinky/bc_idle5.wav
sound/classic/Pinky/bc_pain1.wav
sound/classic/Pinky/bc_pain2.wav
sound/classic/Pinky/bc_pain3.wav
sound/classic/Pinky/bc_pain4.wav
sound/classic/Skull/con_alert1.WAV
sound/classic/Skull/con_alert2.WAV
sound/classic/Skull/con_alert3.WAV
sound/classic/Skull/con_attack1.WAV
sound/classic/Skull/con_attack2.WAV
sound/classic/Skull/con_attack3.WAV
sound/classic/Skull/con_die1.WAV
sound/classic/Skull/con_die2.WAV
sound/classic/Skull/con_idle1.WAV
sound/classic/Skull/con_idle2.WAV
sound/classic/Skull/con_idle3.WAV
sound/classic/Skull/con_idle4.WAV
sound/classic/Skull/con_idle5.WAV
sound/classic/Skull/con_pain1.wav
sound/classic/Skull/con_pain2.wav
sound/classic/Skull/con_pain3.wav
sound/classic/Skull/electro4.WAV
sound/classic/Skull/electro5.WAV
sound/classic/Skull/electro6.WAV
sound/classic/Spider/gon_alert1.WAV
sound/classic/Spider/gon_alert2.WAV
sound/classic/Spider/gon_alert3.WAV
sound/classic/Spider/gon_attack1.WAV
sound/classic/Spider/gon_attack2.WAV
sound/classic/Spider/gon_attack3.WAV
sound/classic/Spider/gon_die1.WAV
sound/classic/Spider/gon_pain2.WAV
sound/classic/Spider/gon_pain4.WAV
sound/classic/Spider/gon_pain5.WAV
sound/classic/Spider/gon_sack1.WAV
sound/classic/Spider/gon_sack2.WAV
sound/classic/Spider/gon_sack3.WAV
sound/classic/Spider/gon_step1.WAV
sound/classic/Spider/gon_step2.WAV
sound/classic/Spider/gon_step3.WAV
sound/classic/Zombieman/claw_miss1.wav
sound/classic/Zombieman/claw_miss2.wav
sound/classic/Zombieman/claw_strike1.wav
sound/classic/Zombieman/claw_strike2.wav
sound/classic/Zombieman/claw_strike3.wav
sound/classic/Zombieman/gr_mgun1.wav
sound/classic/Zombieman/sbarrel1.wav
sound/classic/Zombieman/zo_alert10.WAV
sound/classic/Zombieman/zo_alert20.WAV
sound/classic/Zombieman/zo_alert30.WAV
sound/classic/Zombieman/zo_attack1.WAV
sound/classic/Zombieman/zo_attack2.WAV
sound/classic/Zombieman/zo_idle1.WAV
sound/classic/Zombieman/zo_idle2.WAV
sound/classic/Zombieman/zo_idle3.WAV
sound/classic/Zombieman/zo_idle4.WAV
sound/classic/Zombieman/zo_pain1.WAV
sound/classic/Zombieman/zo_pain2.WAV
