// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

aurora_city.wad
crimecity.wad
dt_nyc_firstbatch.wad
graf00.wad
models/crimecity/barnabus.mdl
models/crimecity/barney1.mdl
models/crimecity/bgman.mdl
models/crimecity/cartel.mdl
models/crimecity/civ.mdl
models/crimecity/copboss.mdl
models/crimecity/copboss01.mdl
models/crimecity/copboss02.mdl
models/crimecity/copboss03.mdl
models/crimecity/gangmember.mdl
models/crimecity/girl1.mdl
models/crimecity/gonome.mdl
models/crimecity/gunhobo.mdl
models/crimecity/hassassin.mdl
models/crimecity/hgrunt.mdl
models/crimecity/hobo/scientist.mdl
models/crimecity/hobo/scientist01.mdl
models/crimecity/hobo/scientist02.mdl
models/crimecity/hobo/scientist03.mdl
models/crimecity/hobo/scientist04.mdl
models/crimecity/hobo/scientist05.mdl
models/crimecity/hobo/scientist06.mdl
models/crimecity/hobo/scientist07.mdl
models/crimecity/hobo/scientistt.mdl
models/crimecity/mobius.mdl
models/crimecity/mobiusmech.mdl
models/crimecity/money.mdl
models/crimecity/p_knife.mdl
models/crimecity/p_m40a1.mdl
models/crimecity/p_pipe_wrench.mdl
models/crimecity/p_shotgun.mdl
models/crimecity/pills.mdl
models/crimecity/props/1.mdl
models/crimecity/props/4.mdl
models/crimecity/props/advanedDark.mdl
models/crimecity/props/appel1.mdl
models/crimecity/props/chair1.mdl
models/crimecity/props/coke_box.mdl
models/crimecity/props/crate.mdl
models/crimecity/props/handfat_lol.mdl
models/crimecity/props/kassa.mdl
models/crimecity/props/polis_bil.mdl
models/crimecity/props/soppase.mdl
models/crimecity/props/tjej_lik_1.mdl
models/crimecity/props/trash3.mdl
models/crimecity/props/trash4.mdl
models/crimecity/rgrunt.mdl
models/crimecity/russianboss.mdl
models/crimecity/scientist.mdl
models/crimecity/scientist01.mdl
models/crimecity/scientist02.mdl
models/crimecity/scientist03.mdl
models/crimecity/scientist04.mdl
models/crimecity/scientist05.mdl
models/crimecity/scientist06.mdl
models/crimecity/scientist07.mdl
models/crimecity/scientistnormal.mdl
models/crimecity/scientistt.mdl
models/crimecity/shotgunshell.mdl
models/crimecity/suits/scientist.mdl
models/crimecity/suits/scientist01.mdl
models/crimecity/suits/scientist02.mdl
models/crimecity/suits/scientist03.mdl
models/crimecity/suits/scientist04.mdl
models/crimecity/suits/scientist05.mdl
models/crimecity/suits/scientist06.mdl
models/crimecity/suits/scientist07.mdl
models/crimecity/suits/scientist08.mdl
models/crimecity/suits/scientist09.mdl
models/crimecity/suits/scientist10.mdl
models/crimecity/twitcher/twitcher.mdl
models/crimecity/v_knife.mdl
models/crimecity/v_m16a2.mdl
models/crimecity/v_m40a1.mdl
models/crimecity/v_pipe_wrench.mdl
models/crimecity/v_shotgun.mdl
models/crimecity/w_knife.mdl
models/crimecity/w_m40a1.mdl
models/crimecity/w_pipe_wrench.mdl
models/crimecity/w_shotgun.mdl
models/crimecity/yakuzaboss.mdl
models/crimecity/zombie.mdl
models/crimecity/zombiet.mdl
sound/crimecity/buy.wav
sound/crimecity/doors/doormove9.wav
sound/crimecity/doors/doorstop4.wav
sound/crimecity/fu.ogg
sound/crimecity/items/pills.wav
sound/crimecity/lessgo.ogg
sound/crimecity/music/Express.wav
sound/crimecity/music/Footsteps.ogg
sound/crimecity/music/Maniac.wav
sound/crimecity/music/MURDER IN MY MIND.wav
sound/crimecity/music/NGHTWLK.wav
sound/crimecity/music/Ravemonkey.ogg
sound/crimecity/music/Rust.wav
sound/crimecity/music/Sayonara.wav
sound/crimecity/weapons/chainsaw_running_idle.wav
sound/crimecity/weapons/chainsaw_start.wav
sound/crimecity/weapons/dbarrel1.wav
sound/crimecity/weapons/dbarrel2.wav
sound/crimecity/weapons/knife_hitbod1.wav
sound/crimecity/weapons/knife_hitbod2.wav
sound/crimecity/weapons/knife_hitwall1.wav
sound/crimecity/weapons/knife_miss.wav
sound/crimecity/weapons/pwrench_big_hitbod1.wav
sound/crimecity/weapons/pwrench_hit1.wav
sound/crimecity/weapons/pwrench_hit2.wav
sound/crimecity/weapons/pwrench_hitbod1.wav
sound/crimecity/weapons/pwrench_hitbod2.wav
sound/crimecity/weapons/pwrench_hitbod3.wav
sound/crimecity/weapons/pwrench_miss1.wav
sound/crimecity/weapons/pwrench_miss2.wav
sound/crimecity/weapons/sbarrel1.wav
sound/crimecity/weapons/sbarrel2.wav
sound/crimecity/zombie/idle.wav
sound/crimecity/zombie/zo_alert10.wav
sound/crimecity/zombie/zo_alert20.wav
sound/crimecity/zombie/zo_alert30.wav
sound/crimecity/zombie/zo_pain1.wav
sound/crimecity/zombie/zo_pain2.wav
sound/crimecity/zombie/zo_pain3.wav
sound/hostage/hos6.wav
sound/hostage/hos7.wav
sound/weapons/chainsaw_running_idle.wav
sound/weapons/chainsaw_start.wav
sprites/crimecity/fu.spr
sprites/crimecity/money.spr
sprites/crimecity/nice.spr
