// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

gfx/env/dmcwbk.tga
gfx/env/dmcwdn.tga
gfx/env/dmcwft.tga
gfx/env/dmcwlf.tga
gfx/env/dmcwrt.tga
gfx/env/dmcwup.tga
models/dmc/armour_r.mdl
models/dmc/armour_y.mdl
models/dmc/b_nail0.mdl
models/dmc/b_nail1.mdl
models/dmc/g_light.mdl
models/dmc/g_nail.mdl
models/dmc/g_nail2.mdl
models/dmc/g_rock.mdl
models/dmc/g_rock2.mdl
models/dmc/g_shot2.mdl
models/dmc/grenade.mdl
models/dmc/p_crowbar.mdl
models/dmc/p_light.mdl
models/dmc/p_nail.mdl
models/dmc/p_nail2.mdl
models/dmc/p_rock.mdl
models/dmc/p_rock2.mdl
models/dmc/p_shot.mdl
models/dmc/p_shot2.mdl
models/dmc/rocket.mdl
models/dmc/shell.mdl
models/dmc/spike.mdl
models/dmc/v_crowbar.mdl
models/dmc/v_light.mdl
models/dmc/v_nail.mdl
models/dmc/v_nail2.mdl
models/dmc/v_rock.mdl
models/dmc/v_rock2.mdl
models/dmc/v_shot.mdl
models/dmc/v_shot2.mdl
models/dmc/w_battery.mdl
models/dmc/w_batteryt.mdl
models/dmc/w_medkit.mdl
models/dmc/w_medkitl.mdl
models/dmc/w_medkits.mdl
models/dmc/w_medkitt.mdl
models/dmc/w_rpgammo.mdl
models/dmc/w_rpgammo_big.mdl
models/dmc/w_rpgammot.mdl
models/dmc/w_shotbox.mdl
models/dmc/w_shotbox_big.mdl
models/dmc/w_shotboxt.mdl
sound/dmc/items/armor1.wav
sound/dmc/items/health1.wav
sound/dmc/items/itembk2.wav
sound/dmc/items/r_item1.wav
sound/dmc/misc/r_tele3.wav
sound/dmc/music/dmc_dm2.ogg
sound/dmc/player/ax1.wav
sound/dmc/player/axhit1.wav
sound/dmc/player/axhit2.wav
sound/dmc/player/gib.wav
sound/dmc/weapons/bounce.wav
sound/dmc/weapons/grenade.wav
sound/dmc/weapons/lhit.wav
sound/dmc/weapons/lock4.wav
sound/dmc/weapons/lstart.wav
sound/dmc/weapons/pkup.wav
sound/dmc/weapons/r_exp3.wav
sound/dmc/weapons/rocket1i.wav
sound/dmc/weapons/sgun1.wav
sound/dmc/weapons/shotgn2.wav
sound/dmc/weapons/spike2.wav
sound/dmc/weapons/tink1.wav
sprites/dmc/320hud2.spr
sprites/dmc/640hud7.spr
sprites/dmc/crosshairs.spr
sprites/dmc/explode1.spr
sprites/dmc/hudcb.spr
sprites/dmc/hudgl.spr
sprites/dmc/hudglammo.spr
sprites/dmc/hudlg.spr
sprites/dmc/hudlgammo.spr
sprites/dmc/hudng.spr
sprites/dmc/hudngammo.spr
sprites/dmc/hudrl.spr
sprites/dmc/hudrlammo.spr
sprites/dmc/hudsg.spr
sprites/dmc/hudsgammo.spr
sprites/dmc/hudsng.spr
sprites/dmc/hudsngammo.spr
sprites/dmc/hudssg.spr
sprites/dmc/hudssgammo.spr
sprites/dmc/smoke.spr
sprites/dmc/weapon_dmc_crowbar.txt
sprites/dmc/weapon_dmc_grenadelauncher.txt
sprites/dmc/weapon_dmc_lightning.txt
sprites/dmc/weapon_dmc_nailgun.txt
sprites/dmc/weapon_dmc_rocketlauncher.txt
sprites/dmc/weapon_dmc_shotgun.txt
sprites/dmc/weapon_dmc_supernailgun.txt
sprites/dmc/weapon_dmc_supershotgun.txt
sprites/dmc/ZBeam1.spr
sprites/dmc/ZBeam2.spr
sound/dmc/misc/talk.wav
sound/dmc/player/death1.wav
sound/dmc/player/death2.wav
sound/dmc/player/death3.wav
sound/dmc/player/death4.wav
sound/dmc/player/death5.wav
sound/dmc/player/drown1.wav
sound/dmc/player/drown2.wav
sound/dmc/player/pain1.wav
sound/dmc/player/pain2.wav
sound/dmc/player/pain3.wav
sound/dmc/player/pain4.wav
sound/dmc/player/pain5.wav
sound/dmc/player/pain6.wav
models/dmc/pow_quad.mdl
models/dmc/pow_invuln.mdl
models/dmc/pow_invis.mdl
sound/dmc/items/damage.wav
sound/dmc/items/damage2.wav
sound/dmc/items/damage3.wav
sound/dmc/items/protect.wav
sound/dmc/items/protect2.wav
sound/dmc/items/protect3.wav
sound/dmc/items/inv1.wav
sound/dmc/items/inv2.wav
sound/dmc/items/inv3.wav
sound/dmc/items/suit.wav
sound/dmc/weapons/ric1.wav
sound/dmc/weapons/ric2.wav
sound/dmc/weapons/ric3.wav