// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/hydramantibk.tga
gfx/env/hydramantidn.tga
gfx/env/hydramantift.tga
gfx/env/hydramantilf.tga
gfx/env/hydramantirt.tga
gfx/env/hydramantiup.tga
models/rngstuff/kyper_kuutio/kyper_assistant.mdl
models/rngstuff/kyper_kuutio/ld_barnabus.mdl
models/rngstuff/kyper_kuutio/mr_zombie3.mdl
models/rngweapons/kyper_kuutio/pee/p_electrogun.mdl
models/rngweapons/kyper_kuutio/pee/p_exoshotgun.mdl
models/rngweapons/kyper_kuutio/pee/p_gausspistol.mdl
models/rngweapons/kyper_kuutio/pee/p_kyperbow.mdl
models/rngweapons/kyper_kuutio/pee/p_microgun.mdl
models/rngweapons/kyper_kuutio/pee/p_mininuke.mdl
models/rngweapons/kyper_kuutio/pee/p_mininuke_r.mdl
models/rngweapons/kyper_kuutio/pee/p_omegacannon.mdl
models/rngweapons/kyper_kuutio/pee/p_sporegun.mdl
models/rngweapons/kyper_kuutio/v_electrogun.mdl
models/rngweapons/kyper_kuutio/v_exoshotgun.mdl
models/rngweapons/kyper_kuutio/v_gausspistol.mdl
models/rngweapons/kyper_kuutio/v_kyperbow.mdl
models/rngweapons/kyper_kuutio/v_microgun.mdl
models/rngweapons/kyper_kuutio/v_mininuke.mdl
models/rngweapons/kyper_kuutio/v_omegacannon.mdl
models/rngweapons/kyper_kuutio/v_sporegun.mdl
models/rngweapons/kyper_kuutio/wee/mininuke_rocket.mdl
models/rngweapons/kyper_kuutio/wee/sporewhite.mdl
models/rngweapons/kyper_kuutio/wee/w_electrogun.mdl
models/rngweapons/kyper_kuutio/wee/w_exoshotgun.mdl
models/rngweapons/kyper_kuutio/wee/w_gausspistol.mdl
models/rngweapons/kyper_kuutio/wee/w_kyperbow.mdl
models/rngweapons/kyper_kuutio/wee/w_microgun.mdl
models/rngweapons/kyper_kuutio/wee/w_mininuke.mdl
models/rngweapons/kyper_kuutio/wee/w_mininuke_ammo.mdl
models/rngweapons/kyper_kuutio/wee/w_omegacannon.mdl
models/rngweapons/kyper_kuutio/wee/w_sporegun.mdl
models/rngweapons/p_rngmace.mdl
models/rngweapons/v_rngmace.mdl
models/rngweapons/w_rngmace.mdl
sound/rng/kyper_kuutio/kyper_kuutio4_loop.ogg
sound/rng/kyper_kuutio/kyper_kuutio_outro.ogg
sound/rng/kyper_kuutio/kyper_kuutio_ship.wav
sound/rng/kyper_kuutio/kyper_kuutio_ship2.wav
sound/rng/kyper_kuutio/kyper_kuutio_trigger2.wav
sound/weapons/saw_boltout.wav
