// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/hatuhinodebk.tga
gfx/env/hatuhinodedn.tga
gfx/env/hatuhinodeft.tga
gfx/env/hatuhinodelf.tga
gfx/env/hatuhinodert.tga
gfx/env/hatuhinodeup.tga
models/hidoi_map/yasHD.mdl
models/hidoi_map/yasHDt.mdl
models/player/uboa/uboa.bmp
models/player/uboa/uboa.mdl
models/road_to_shinnen/aan_takored.mdl
models/road_to_shinnen/aan_takowhite.mdl
models/road_to_shinnen/electro_takoyaki.mdl
models/road_to_shinnen/fukuwarai_hana.mdl
models/road_to_shinnen/fukuwarai_hoppe.mdl
models/road_to_shinnen/fukuwarai_kuchi.mdl
models/road_to_shinnen/fukuwarai_mayu.mdl
models/road_to_shinnen/fukuwarai_meL.mdl
models/road_to_shinnen/fukuwarai_meR.mdl
models/road_to_shinnen/gamesaba_takoyaki.mdl
models/road_to_shinnen/hugecrowbar.mdl
models/road_to_shinnen/otoshidama.mdl
models/the_daikon_warfare/chatarou.mdl
models/the_daikon_warfare/takeobj.mdl
models/uboa/ichybarney.mdl
models/uboa/ichybarneyT.mdl
sound/road_to_shinnen/enuzehlss/kichigaidaa.wav
sound/road_to_shinnen/enuzehlss/kichigaika.wav
sound/road_to_shinnen/enuzehlss/kichigaizatadayo.wav
sound/road_to_shinnen/enuzehlss/mattakukono.wav
sound/road_to_shinnen/enuzehlss/wkmtmega2.wav
sound/road_to_shinnen/enuzehlss/wkmtstsc.wav
sound/road_to_shinnen/harunoumi.mp3
sound/road_to_shinnen/karuta_ha.wav
sound/road_to_shinnen/karuta_he.wav
sound/road_to_shinnen/karuta_ho.wav
sound/road_to_shinnen/karuta_i.wav
sound/road_to_shinnen/karuta_ni.wav
sound/road_to_shinnen/karuta_otetuki.wav
sound/road_to_shinnen/karuta_ro.wav
sound/road_to_shinnen/saisen.wav
sound/road_to_shinnen/suzu.wav
sound/road_to_shinnen/warai.wav
sound/takedeppo/50cal_fire.wav
sound/takedeppo/50cal_fun_time.wav
sound/uboa/ichybarney/ichy_alert1.wav
sound/uboa/ichybarney/ichy_alert2.wav
sound/uboa/ichybarney/ichy_alert3.wav
sound/uboa/ichybarney/ichy_attack1.wav
sound/uboa/ichybarney/ichy_attack2.wav
sound/uboa/ichybarney/ichy_bite1.wav
sound/uboa/ichybarney/ichy_bite2.wav
sound/uboa/ichybarney/ichy_die1.wav
sound/uboa/ichybarney/ichy_die2.wav
sound/uboa/ichybarney/ichy_die3.wav
sound/uboa/ichybarney/ichy_die4.wav
sound/uboa/ichybarney/ichy_idle1.wav
sound/uboa/ichybarney/ichy_idle2.wav
sound/uboa/ichybarney/ichy_idle3.wav
sound/uboa/ichybarney/ichy_idle4.wav
sound/uboa/ichybarney/ichy_pain1.wav
sound/uboa/ichybarney/ichy_pain2.wav
sound/uboa/ichybarney/ichy_pain3.wav
sound/uboa/ichybarney/ichy_pain4.wav
sound/uboa/ichybarney/ichy_pain5.wav
sound/uboa/nekomimi.wav
sound/votemap/psycho.wav
